Yoast/wpseo-news

classes/class-meta-box.php, classes/class-sitemap.php, wpseo-news.php
Did some refactoring for the standout and fixed some other duplicate code.
=> Standout tag refactoring

classes/class-meta-box.php, classes/class-sitemap-editors-pick.php, classes/class-sitemap.php, wpseo-news.php
=> Only use selected post types for editors pick [Finishes #80892074]

classes/class-sitemap.php
=> Fix the stylesheet when sitemap is served from cache

classes/class-sitemap.php, codesniffer.xml
=> Remove htmlspecialchars from output where cdata is used

README.md, wpseo-news.php
=> Release notes and version bump 2.2.4

classes/class-meta-box.php
=> Check if the result of `get_metabox_post` is an instance of `WP_POST`

.gitignore, tests/bootstrap.php, wpseo-news.php
Added missing WP_PLUGIN_DIR check in bootstrap.php and removed an obsolete wpseo_admin_pages filter. Fixes #176
=> Removed obsolete filter and updated bootstrap.php

classes/class-product.php
See https://github.com/Yoast/wordpress-seo-premium/pull/468
=> Use HTTP for the license manager

.travis.yml, assets/xml-news-sitemap-xsl.php, classes/class-beacon-setting.php, classes/class-beacon-suggestions.php, classes/class-wpseo-news.php, composer.json, composer.lock
=> Implement beacon using yoast/wp-helpscout

classes/class-product.php, classes/class-wpseo-news.php
=> fix enqueue in nonexistent directory

composer.json, composer.lock
Fixes autoload generation failing on latest Composer versions.
=> Updated composer-php52 dependency

.travis.yml, classes/class-admin-page.php, classes/class-product.php, classes/class-sitemap.php, classes/class-wpseo-news.php, codesniffer.xml, composer.json, composer.lock, phpcs.xml, phpunit.xml, tests/bootstrap.php, tests/test-class-sitemap.php, wpseo-news.php
Instead of checking for items to add a filter on the `wpseo_sitemap_index` always add the filter and check inside if we need to modify anything.
Fixed several codestyle problems on this file.
Fixed codestyle config.
Updated composer yoast codestyle version.
Fixes #224
=> get_items optimization

classes/class-head.php, classes/class-meta-box.php
=> Add option to noindex the post for Google News

README.md
=> changelog for 3.5

classes/class-admin-page.php, classes/class-editors-pick-request.php, classes/class-meta-box.php, classes/class-sitemap-editors-pick.php, tests/test-class-admin-page.php
Fixes #237 
For now this PR just changes the buttons to make them look like links because they're links. Also, makes a small change to a string, and improves a bit the spacing between the sections. Needs some good idea for a better wording to avoid the word "here" :)
=> Better alignments and accessibility.

classes/class-meta-box.php
* Add check to verify if current page is not the quick-edit one.
* Follow the steps to reproduce the issue.
Fixes #196
=> Add check to verify is saving is not happening on inline-save.

README.md
=> Adds changelog for 3.8

classes/class-head.php
See https://github.com/Yoast/wpseo-news/pull/171
Fixes #140
=> Fixes W3C validation error on <link attribute 'original-source'

README.md
=> Adds changelog for 4.1

README.md
=> Changelog for 4.2

README.md
Adds changelog 4.3
BEFORE merging, please change the base branch to the current release branch!
=> Adds changelog 4.3

.travis.yml, phpunit.xml, tests/test-class-sitemap.php
=> Fixes references to calculate testcoverage

classes/class-sitemap-editors-pick.php
* Fixes a bug where the date format is invalid
* Define the format hardcoded instead of using a constant.
* Have some posts in the editors pick.
* Validate the editors pick by using this link: https://validator.w3.org/feed/
Fixes #290
Fixes #241
=> Use the right dateformat for the published on date

.travis.yml, classes/class-meta-box.php, classes/class-sitemap-editors-pick.php, tests/test-class-sitemap-editors-pick.php
Update the travis config to make sure newer php and wp version are tested.
=> Update the travis test matrix

assets/xml-news-sitemap-xsl.php, classes/class-admin-page.php, classes/class-beacon-setting.php, classes/class-editors-pick-request.php, classes/class-head.php, classes/class-javascript-strings.php, classes/class-meta-box.php, classes/class-meta-keywords.php, classes/class-product.php, classes/class-sitemap-editors-pick.php, classes/class-sitemap.php, classes/class-upgrade-manager.php, classes/class-wpseo-news.php
* I was checking the codestyle locally and there were a lot of codestyle issues regarding documentation. I fixed those
* I mostly changed the codestyle, but there is a minor change for the editors pick. Please check if this still works.
=> Fix codestyle

classes/class-product.php
* Changes the license lookup endpoint to my.yoast.com
=> Make sure the endpoint goes to my.yoast.com

classes/class-meta-keywords.php, classes/class-sitemap.php, composer.json, composer.lock, wpseo-news.php
* Upgrade Yoast Coding Standards to the latest version.
=> Upgrade YoastCS to latest version

assets/xml-news-sitemap-xsl.php
This PR can be summarized in the following changelog entry: Fix jquery.tablesorter.min.js URL
* View the news sitemap and check if table can be sorted.
Fixes #323
=> Fix jquery.tablesorter.min.js URL

.travis.yml
Fixes https://github.com/Yoast/wordpress-seo/issues/8415
=> Bump PHP and WordPress versions in travis

.travis.yml, phpunit.xml
Fix coverage build
See https://github.com/Yoast/wordpress-seo/commit/cdbe7acab274689e46c366ad182bdc703272e7dd
=> Disable xdebug for non coverage build

classes/class-admin-page.php, classes/class-beacon-setting.php, classes/class-meta-box.php, classes/class-sitemap-editors-pick.php, classes/class-sitemap.php, classes/class-upgrade-manager.php, tests/assets/wpseo-news-double.php, tests/framework/class-wpseo-news-unit-test-case.php, tests/test-class-admin-page.php, tests/test-class-sitemap-editors-pick.php, tests/test-class-sitemap.php
_N/A_
Various whitespace fixes + one missing comma after last array item.
This PR will be easiest to review using the `?w=1` trick on the files tab
_N/A_
=> CS: fix a variety of whitespace issues

tests/framework/class-wpseo-news-unit-test-case.php
_N/A_
Just removing a parameter which isn't used in the function anyway.
_N/A_
=> CS/QA: remove unused function parameter

tests/index.php
* _N/A_
Tests should not be shipped with the plugin, so this directory should never end up in a user-install and therefore does not need an empty `index.php` file.
=> CS/QA: remove superfluous index.php file

tests/test-class-sitemap.php
=> CS: fix unnecessary usage of double quotes

README.md, wpseo-news.php
* _Renewed compatibility with the [Plugin Dependencies](http://wordpress.org/plugins/plugin-dependencies/) plugin._
* Fixes compatibility with the [Plugin Dependencies](http://wordpress.org/plugins/plugin-dependencies/) plugin.
* Activate the Plugin Dependencies plugin
* Using the `master` branch: open the plugins page and do **not** see the dependencies correctly identified.
* Using this branch: open the plugins page and see the dependencies correctly identified.
=> Update `Depends` header

classes/class-wpseo-news.php
All output should be escaped, including translations.
Includes minor code build up/layout changes.
Test this by checking that the admin notices which display when WPSEO is missing or not at the correct version and when WP is not at the correct minimum version still display correctly.
=> CS/XSS: always escape output [2]

classes/class-wpseo-news.php
_N/A_
* Code style compliance - minor whitespace/code layout fixes.
_N/A_
=> CS: clean up after latest merges

classes/class-sitemap.php
* Security hardening
Queries with a variable number of replacements can be prepared as well.
The placeholders are dynamically created using an `implode( ',', array_fill( 0, $count, '%s' ) )` and the complete set of replacements need to be passed as an array in the second parameter of `prepare()`.
Includes:
* Prepare late, i.e. wrap the call to `prepare()` within the query call.
* Remove a `private` method which previously did some work for the `IN` clause.
* Verify that the sitemap still displays all the items expected.
* With a debug tool - check that the SQL query created and run is correct.
=> CS/SQL: refactor query using ` IN ()`

classes/class-admin-page.php, classes/class-beacon-setting.php, classes/class-editors-pick-request.php, classes/class-head.php, classes/class-javascript-strings.php, classes/class-meta-box.php, classes/class-news-wrappers.php, classes/class-product.php, classes/class-sitemap-editors-pick.php, classes/class-sitemap-images.php, classes/class-sitemap-item.php, classes/class-sitemap-timezone.php, classes/class-sitemap.php, classes/class-upgrade-manager.php, classes/class-wpseo-news.php, tests/assets/wpseo-news-double.php, tests/bootstrap.php, tests/framework/class-wpseo-news-unit-test-case.php, tests/test-class-admin-page.php, tests/test-class-sitemap-editors-pick.php, tests/test-class-sitemap.php, tests/test-class-wpseo-news.php, wpseo-news.php
_N/A_
Fix up the documentation. Please see the individual commits for more detail.
_N/A_
=> Documentation: various fixes

tests/test-class-sitemap.php
* Changes a test to make it compatible with PHP 5.2.
* Ensure the tests pass.
=> Redid the tests to make them compatible with PHP 5.2

classes/class-head.php, classes/class-meta-box.php, classes/class-upgrade-manager.php
=> Cherry pick pull

.travis.yml
* N/A
*Added needed things for the deploy as discussed with @atimmer
=> Replaced a regex and added a env variable.

classes/class-product.php
* Make sure changelog shows up for updates.
* Apply patch, change version number, see changelog.
Fixes #420
=> Fix API endpoint URL

wpseo-news.php
=> CodeCoverage: ignore deprecated method(s)

classes/class-sitemap-item.php, tests/assets/wpseo-news-double.php, tests/test-class-admin-page.php, tests/test-class-sitemap.php
* _N/A_
* Documentation compliance.
* _N/A_
=> Documentation: minor fixes

tests/assets/wpseo-news-sitemap-item-double.php
=> CS: PHP keywords should be lowercase

classes/class-meta-box.php, classes/class-sitemap-timezone.php, classes/class-wpseo-news.php, tests/test-class-admin-page.php, tests/test-class-sitemap-item.php, tests/test-class-sitemap.php
=> CS: various minor whitespace issues

tests/test-class-sitemap.php
* _N/A_
* Add some missing docblocks.
* Add missing short descriptions 
* _N/A_
=> Test documentation: fix missing docs

classes/class-sitemap-timezone.php, classes/class-wpseo-news.php, tests/framework/class-wpseo-news-unit-test-case.php
* _N/A_
Assignments in conditions makes for hard to debug, hard to read code and is considered a code smell.
* _N/A_ / This is a code-only change and shouldn't affect functionality.
=> CS/QA: don't use assignments in conditions

.travis.yml, classes/class-wpseo-news.php, tests/test-class-wpseo-news.php
=> Bump minimal required version to 10.2-rc0

README.md
* N/A
* Bump tested up to version to 5.2
* N/A
Fixes #
=> Bump tested up to version to 5.2

classes/schema.php, classes/sitemap.php
* _N/A_
* Code style compliance. Minor fixes to recently introduced code.
* _N/A_
=> CS: clean up

classes/admin-page.php, classes/excludable-taxonomies.php, classes/meta-box.php, classes/wpseo-news.php, integration-tests/meta-box-test.php, integration-tests/schema-test.php, tests/TestCase.php
* _N/A_
CS fixes after recent merges.
* _N/A_
=> CS: clean up after merges

README.md
* Sets the minimum required WordPress version to 5.2, and the minimum PHP version to 5.6.20.
* N/A
* N/A
Fixes #
=> Set tested up to to 5.3, minimum wp to 5.2 and PHP to 5.6.20

phpunit-integration.xml.dist, phpunit.xml.dist
* _N/A_
* Use indentation to improve readability.
* Tabs vs spaces - consistently use tabs.
* Consistent content of the `filter` `whitelist` entry.
* _N/A_
=> Tidy up PHPUnit config files

tests/bootstrap.php
* _N/A_
Basically the same change as previously made in #504, but now for the newly introduced BrainMonkey based tests.
* Throw away the `vendor` directory and try to run the unit tests. See a fatal error.
* Switch to this branch, do the same, see a helpful error message.
=> PHPUnit bootstrap: friendly error message

classes/schema.php
=> Renamed the class we have to use

integration-tests/sitemap-item-test.php
=> CS: minor clean up after merges

classes/sitemap.php
=> CS: minor whitespace fix

classes/sitemap-images.php, classes/wpseo-news.php, integration-tests/bootstrap.php
* _N/A_
Don't use Yoda conditions.
* _N/A_
=> CS: don't use Yoda conditions

integration-tests/sitemap-item-test.php
* _N/A_
* _N/A_
This is a test-only change. If the tests still pass, we're good.
=> QA: remove unused variable

tests/testcase.php
=> QA:  use FQN function calls in namespaced files

classes/wpseo-news.php, integration-tests/wpseo-news-test.php
*
* Set minimum WP version to 5.3
*
*
Fixes #
=> Set minimum WP version to 5.3

tests/googlebot-news-presenter-test.php, tests/news-test.php
Always be explicit about which classes are being used in a namespaced file, even when it's a class from within the same namespace.
* _N/A_
=> QA: add missing import `use` statements for classes

classes/meta-box.php
* QA: remove useless variable
* QA: remove useless variable
Lower memory usage by not assigning to a variable when all that's being done is return the same.
* _N/A_
=> QA: remove useless variable

classes/meta-box.php, classes/wpseo-news.php, tests/googlebot-news-presenter-test.php
* Docs: various minor fixes
*  Minor improvements to the documentation.
* Annotate unused function parameter.
* Improve param/return type specificity.
* Use FQN names for classes/interfaces in docblocks.
* _N/A_
=> Docs: various minor fixes

.travis.yml
* CI build env stability
* CI build env stability
*
* _N/A_
=> Travis: add OS key

tests/news-test.php, tests/testcase.php
* Code style consistency
* Code style consistency
*
* _N/A_
=> CS: order `use` statements alphabetically

classes/schema.php, integration-tests/schema-test.php
* Pages have the default article type of `None` (and this can not be changed), but still have author support. They should be able to be changed to `NewsArticle`.
* Fixes a bug where the schema article would not be output for `Pages` and other post types with author support that have their current article type set to `None`.
* Use `wpseo_schema_article_type` to change the type, because the `is_needed` checks the type. And the `wpseo_schema_article` won't be triggered if the type is `None`.
* When the type includes `None`, this is changed to `Article` to make it consistant with post types that are not set to `None`. E.g. the `@type` will end up as `[ "Article", "NewsArticle" ]`, and not just `"NewsArticle"`.
This PR can be tested …
=> P1-125 Fix NewsArticle not working when the current article type is None

tests/news-test.php, tests/option-test.php
* Improve automated testing
* Improve automated testing
*  Unit tests: use strict assertions
* Unit tests: use named test cases in data provider 
* _N/A_ If the builds which run the tests pass, we're good.
=> Tests: further improvements

integration-tests/meta-box-test.php, integration-tests/schema-test.php
* Improve tests
* Improve tests
*
* _N/A_ If the test builds pass, we're good.
=> Unit tests: use strict assertions and use correct assertions

Gruntfile.js
* As plugin-grunt-tasks has been updated, the workaround for .sass files is no longer needed.
* As plugin-grunt-tasks has been updated, the workaround for .sass files is no longer needed.
*
* As this is devtooling no further testing is required
*
*
Fixes #
=> remove grunt watch sass workaround

.travis.yml
* 
* Updates the security checker to fix the build.
*
*
*
*
Fixes #
=> replace security checker

.travis.yml, README.md, integration-tests/wpseo-news-test.php
* On March 9th, WordPress 5.7 will be released. We always support the 2 latest versions.
* Sets the WordPress tested up to version to 5.7 and minimum supported WordPress version to 5.6.
* N/A
*  N/A
* 
*  N/A
Fixes #
=> Set tested up to to WP 5.7 and minimum to 5.6

classes/javascript-strings.php, classes/meta-box.php, classes/wpseo-news.php, config/composer/actions.php, tests/news-test.php
Various minor CS/QA tweaks
* _N/A_ This PR contains no functional changes. If the build passes, we're good.
=> CS: various minor tweaks

README.md
* Harmonise The changelog style to reflect the style used across yoast addons
* Harmonise The changelog style to reflect the style used across yoast addons
*
*
*
*
Fixes #
=> add Earlier versions to READme.md

classes/wpseo-news.php
* We support the last two released versions of WordPress.
* Sets the minimum WordPress version to 5.6.
*
* No need to test this PR.
*
*
Fixes #
=> Set the minimum required WP version to 5.6

config/jenkins/Jenkinsfile_artifact
Create a Zip file of the plugin for the following branches:
trunk
feature*
release*
* Added Jenkinsfile to automatically build zip files
* Build using Jenkins CI
* Push your Changes.
* Wait until build is complete
* Download the Created ZIP
* Upload zip to test site
*
* None
Fixes #
=> Add Jenkinsfile for Artifact Build

package.json, yarn.lock
* Update grunt-plugin-tasks to 2.1.2
*
*
*
*
Fixes #
=> Update grunt-plugin-tasks to 2.1.2

js/src/components/Sidebar.js
*
* Fixes a bug where a duplicate News section would be shown in the Yoast sidebar in the post editor when Yoast SEO Premium is active.
*
* Use the following test-instructions: https://github.com/Yoast/wordpress-seo/pull/17304
*
*
Fixes #
=> Added key to SidebarItem

.adr-dir, docs/project-decisions/0001-record-architecture-decisions.md
*
* Adds Architecture Decision Records to document project decisions.
*
*
*
*
Fixes #
=> AR-238 Record architecture decisions

classes/product.php, wpseo-news.php
* Fix links to yoast.com to include tracking parameters.
* None needed.
* See links are replaced with shortlinks.
Fixes IM-1280
=> Fix shortlinks

.gitignore
* The entire languages folder was excluded instead of the files in the folder. this caused problems with the release script.
* Fixes a bug where language files would not be stored in Git history.
*
* run the pre-release script to build an RC 
* this change has been reviewed by @herregroen and tested by @noud-github 
*
*
Fixes #
=> ignore all files in folder instead of the entire folder

classes/upgrade-manager.php
* We want to delay the updating of the excluded terms options to the new format (see #721) to make sure we have all CPTs registered by then 
* Fixes an unreleased bug where excluded terms options fo custom post types were lost in the upgrade to 13.1
* We've delayed the upgrade to the `init` hook with priority `100` because it's our standard for the assumption that all CPTs are registered (e.g. `enrich_defaults` in the options classes run at `init` `99`)
* Install and activate Free 17.6
* install and activate Local SEO
* install and activate News SEO 13.0 or `master`
* create some new Location categories
* visit the News SEO settings, enable the sitemap for Locations and …
=> DUPP-76 Delay the update of excluded terms options to have all CPTs registered

yarn.lock
* Bump plugin-grunt-tasks to 2.2.1 This fixes a changelog issue during hotfix creation
* Bump plugin-grunt-tasks to 2.2.1 This fixes a changelog issue during hotfix creation
*
*
*
*
Fixes #
=> Bump plugin-grunt-tasks to 2.2.1

classes/schema.php, classes/sitemap.php, integration-tests/sitemap-test.php
* Remove redundant variables names in return tags.
* Minor tag order tweak.
* Actually _use_ a `use` statement.
* Remove method which became redundant after de65c92f1e6284c69a7d54b72befbebaab692506
* _N/A_ These are code only changes. If the build passes, we're good.
=> CS/QA: various minor changes

.travis.yml
* Fix the CI
* Fix the CI
Allow for 5.9.x.
* _N/A_ If the build passes (again), we're good.
=> Travis: get the builds passing again

.github/workflows/integrationtest.yml, README.md, classes/wpseo-news.php, integration-tests/wpseo-news-test.php
* Sets minimum WordPress version to 5.9 and tested up to 6.0.
* Sets minimum WordPress version to 5.9 and tested up to 6.0.
*
*
*
*
Fixes #
=> Sets the minimum WP version to 5.9 and tested up to 6.0

integration-tests/framework/unittestcase.php
*
* _N/A_ If the build passes, we're good.
=> CS: minor tweaks

.github/workflows/cs.yml, .github/workflows/integrationtest.yml, .github/workflows/js.yml, .github/workflows/lint.yml, .github/workflows/unittest.yml
*
* Prepare repository for renaming master to main
*
*
*
*
Fixes #
=> Rename relevant master references to main

README.md, integration-tests/wpseo-news-test.php
* Sets the tested up to WordPress version to 6.1.
* Sets the tested up to WordPress version to 6.1.
*
* N/A
*
* N/A
Fixes #
=> Set tested up to version to 6.1

.github/workflows/deploy.yml
Follow up to PR #766 which included introducing cache-busting.
Missed one workflow. Fixed now.
* _N/A_
=> GH Actions: update cache-busting

tests/googlebot-news-presenter-test.php, tests/news-test.php, tests/option-test.php
*
* This is a test-only change. If the builds pass, we're good.
=> Tests: use import `use` statements for all referenced WP native classes

wpseo-news.php
* Update the author URI to a new link.
* Updates the author uri value.
*
* Check if the `team yoast` url is the same as described in https://github.com/Yoast/wordpress-seo-premium/issues/3779
*
*
Fixes #
https://github.com/Yoast/wordpress-seo-premium/issues/3779
=> Updates author URI.

README.md, integration-tests/wpseo-news-test.php
* Sets the tested up to WordPress version to 6.2.
* Sets the tested up to WordPress version to 6.2.
*
* N/A
*
* N/A
Fixes #
=> Set the WordPress tested up to version to 6.2

config/scripts/install-wp-tests.sh
Re-synced with the script from the WP-CLI scaffold-command repo.
Ref: https://github.com/wp-cli/scaffold-command/blob/eb8d71618de1e34264991109f91a8d8247601fb2/templates/install-wp-tests.sh
* _N/A_ If the integration tests still run and pass, we're good.
=> Integration tests: update script to install WP

composer.lock
* Update dev dependencies
* Update dev dependencies
Ref: https://github.com/Yoast/PHPUnit-Polyfills/releases/tag/1.0.5
* _N/A_ If the tests run & pass, we're good.
=> Composer: update PHPUnit Polyfills

.github/PULL_REQUEST_TEMPLATE.md
* Updating PR template to allow user to not miss log time for innovative projects, check that correct base branch is selected.
* Update PR template to not miss log time for innovative projects, check that correct base branch is selected.
*
* No testing is required.
*
*
Fixes #[20402](https://github.com/Yoast/wordpress-seo/issues/20402)
=> Update templates to include list of tickets and base branch check.#20402
