Yoast/wpseo-news

classes/class-sitemap.php

$attachment->guid is not necessarily the actual image URL and should not
used to extract an attachment image URL.
I changed the code to use the function wp_get_attachment_url() which is
the documented way to get an URL for an attachment.
References:
http://pods.io/2013/07/17/dont-use-the-guid-field-ever-ever-ever/
http://codex.wordpress.org/Function_Reference/wp_get_attachment_url

Bugfix: changed attachment URL generation

---

classes/class-sitemap.php

Check if $cats is an array before looping through it, as $cats = [get_the_terms](http://codex.wordpress.org/Function_Reference/get_the_terms), which returns an array, false or a wp_error. [fixes #125]

Stories/cg/check cat array before loop [finishes #90493004] [fixes #125]

---

classes/class-meta-box.php

The post wasn't there because we hook to early. Please verify for side effects on this.
Fixes #164

Hooking on the right action to be sure the post is loaded at that point.

---

classes/class-meta-box.php

Fixes #145 
When the meta box got registered, it did a query for the description.
This is unnecessary on all pages except post edit page.
One concern with this solution is, if there would be default values in
the metabox registration, the defaults wouldn't be taken into account
when getting the values. But because News SEO doesn't have any defaults,
this is not an issue.

Remove query call on all pages except post edit

---

classes/class-wpseo-news.php

related to https://github.com/Yoast/wordpress-seo-local/issues/458#issuecomment-188829155
Just like in Local SEO, this filter is no longer relevant.

wpseo_admin_pages is no longer being used in Yoast SEO. So it can be removed

---

classes/class-product.php

Implemented slug and file parameters of the License Manager to facilitate Shiny Update routine to work.
See https://github.com/Yoast/wordpress-seo-premium/issues/274

Fix Shiny Update routine

---

classes/class-admin-page.php
tests/test-class-admin-page.php
wpseo-news.php

Fixes #191 
Currently the Translation box for the addons is always showing the Yoast SEO translation box, if Yoast SEO itself isn't fully translated yet in the language that is selected.
Ideally we want to show the News Translation box, as the translation box will not be shown if Yoast SEO is fully translated, even though News isn't yet (fully) translated, as shown below. This pull fixes that. 
Languages to test with:
Yoast SEO fully translated - News SEO partially/not: choose Catalan for language.
Yoast SEO not fully translated - News SEO not fully translated: choose for example Nederlands (Formeel)

Add i18n module for News

---

classes/class-admin-page.php
tests/test-class-admin-page.php

Only load i18n promo when current page is a `news seo` page. 
This pull request needs pr https://github.com/Yoast/wordpress-seo/pull/4600 to be merged first.

Change i18n promo logic

---

classes/class-beacon-setting.php

`get_config( $page  )` will be added to the `Yoast_HelpScout_Beacon_Setting` interface to alter the help scout beacon's configuration. This allows for all instances of the help scout beacon to be set up differently. ([possible values](http://developer.helpscout.net/beacons/customization/#config-configobject-))

updated helpscout interface

---

classes/class-admin-page.php
classes/class-sitemap.php
tests/test-class-sitemap.php

The publishdate should be in W3C format when the timezone is set in UTC-format. When the timezone is set in UTC format, give the user a notice.
Fixes #112

Publishdate w3c format

---

classes/class-meta-box.php

The hook to add metafields was only edit when being on a post add/edit page. This resulted in errors when opening sitemap, because a value couldn't be found. In order to fix this I've added news-sitemap.xml also.
Fixes #216

Add hook also for the sitemap, because it has to be loaded

---

classes/class-sitemap.php

* Fixes an issue where a page or post type with the slug `news` would be inaccessible.
The rewrite rule would just be `news` or `yoast-news` which is far too broad for only targeting the news sitemap xsl. Improve this by adding `-sitemap.xml` after the basename and also surrounding with ^ and $.
* Have a post that starts with `news`.
* Go to that post.
* Observe that it doesn't work.
Other test cases that should be tested because of full coverage
* Testing with a post type that has a slug of `news`. (Making sure that the sitemap is now at `yoast-news-sitemap.xml`)
#251 is a known bug that is also introduced in 3.5 but has a lesser severity.
Fixes #248

Make xsl rewrite rule more specific

---

classes/class-admin-page.php
classes/class-sitemap.php
tests/test-class-sitemap.php

Removes the wrapping `CDATA` tag from the site name in the News sitemap.
* Create a new post.
* Go to the News sitemap.
* Ensure that the `news:name` property no longer contains a wrapping `CDATA` tag.
Fixes #218

Removed CDATA tag from the name XML property

---

classes/class-meta-box.php

After discussing this with @IreneStr, we decided to write '7 days'
instead of 'seven days'. This way there is more consistency.
Fixes #186

Changed 'seven' to '7' in message about standout tag

---

classes/class-wpseo-news.php

News SEO was translatable in some cases. As this is a plugin name, we do not want this to be translatable. 
Fixes #210

Made sure 'News SEO' is not translatable

---

tests/test-class-sitemap-editors-pick.php
tests/test-class-sitemap.php

Fixes broken tests that throw a deprecated warning.
* Run the tests in PHPUnit / Travis and ensure they pass.

Fixed tests throwing deprecated warning

---

classes/class-sitemap.php

Only invalidate sitemap cache when an object in a Post Type that is marked as News is updated.
*
* Before this patch 'Pages' triggered News sitemap invalidations, with the patch applied they should not (unless manually configured in the News SEO options)
Fixes https://github.com/Yoast/wpseo-news/issues/271

Invalides only on supported Post Types

---

classes/class-sitemap.php
tests/test-class-sitemap-editors-pick.php
tests/test-class-sitemap.php

Replaced deprecated function wpseo_invalidate_sitemap_cache with WPSEO_Sitemaps_Cache::invalidate
1.Have Yoast SEO 4.3
2.Have News SEO 4.3
3.Go to Post->Add New and see warning at top
Fixes #282

Replaced deprecated function wpseo_invalidate_sitemap_cache

---

classes/class-sitemap-editors-pick.php

* [Bugfix] Fixes a bug where sticky posts show up in the editors pick
* Ignore the sticky posts
* Follow the steps in the issue and see this pull fixes the issue.
Fixes #296

Ignore the sticky posts

---

classes/class-admin-page.php

* [Enhancement] Add posttype name after the label to clearify the posttype
*
* Open the news seo page and see it is more clear
Fixes #256

Add posttype name after the label to make it more clear.

---

classes/class-meta-box.php

* [Bug][Compatibility] Fixes a incompatibility bug for Piklist, bbPress andLiveblog (Automattic)
* The `WP_Query` was executed too early, so set the value that relies on it later.
* The pull fixes some errors with the PikList #262, Liveblog #242 and bbPress #243 plugins
* Follow each step below for each plugin
* Checkout `trunk`
* Follow the steps to reproduce the issue in the mentioned issues
* Checkout this branch
* Follow the steps again and see it being solved
Fixes #262
Fixes #242
Fixes #243

Set value later, when value is needed.

---

.travis.yml

This is not a permanent fix, as support will be dropped in September.
See also https://core.trac.wordpress.org/changeset/41072/

Set specific dist for PHP 5.2 and PHP 5.3

---

classes/class-wpseo-news.php

* Deprecated `WPSEO_News::get_sitemap_name` because we have `WPSEO_News_Sitemap::get_sitemap_name` that does the same magic.
* This method  `WPSEO_News::get_sitemap_name` was calling a deprecated function. I was replacing the deprecated call by the one that replaces it, but found out there is a similar method (`WPSEO_News_Sitemap::get_sitemap_name`) that does the same. Because of there are no calls to `WPSEO_News::get_sitemap_name` I deprecated it.
* Check if everything stil works.

Deprecate method for getting the sitemap name.

---

classes/class-admin-page.php
composer.json
composer.lock

Updates the `yoast/i18n-module` to the `^2.0` version and changed the reference to the old version.
* Enable the News SEO plugin with this branch.
* Ensure you have a language selected that **isn't** `en_US` and determine that translations show up, assuming the selected language has them.
Replaces #288

Updated i18n module and references to the old version

---

.travis.yml
classes/class-wpseo-news.php

* Use the capabilities introduced in Yoast SEO 5.5 for menu registration.
* Apply patch and see the menu item being displayed when the current user has `wpseo_manage_options`

Change to new WPSEO Manage Options

---

assets/xml-news-sitemap-xsl.php
assets/xml-news-sitemap.xsl
classes/class-sitemap.php

* Load the XSL stylesheet from a static file. This resulted in removing the tablesorter dependency.
* First of all: remove all transients, to make sure no cache has been loaded.
* Checkout trunk
* Open the news sitemap (you might have to add a post to have 'news') and see tablesorting is working
* Remove all transients again
* Checkout this branch and see the table sorting not working.
Whenever the home URL and site URL are set to different values (local.wordpress.test/local.wordpress-home.test) the XSL needs to be loaded via the previously implemented method.
Otherwise the domain, protocol or port will mismatch and the XSL cannot be loaded.
* Configure home URL to be different from …

Load xsl stylesheet inline

---

classes/class-wpseo-news.php
composer.json
tests/assets/wpseo-news-double.php
tests/test-class-wpseo-news.php

* Show a notice when a WordPress SEO version below 7.0 is installed.
* Have this branch and WordPress SEO active. Change in WordPress SEO the value of constant `WPSEO_VERSION` in a value below 7.0
* A notice should be shown. 
* Change the value of the constant to 7.0 or 7.1 and see the notice being gone.
* Add this somewhere in `wpseo-news.php` to test the minimal required WordPress notification.
```
add_action( 'admin_init', function() {
global $wp_version;
$wp_version = 4.7;
} );
```
Fixes #339 
Fixes #346

Add WordPress SEO version requirement

---

README.md

This new header has been soft launched on August 25th 2017.
Refs:
* https://meta.trac.wordpress.org/ticket/2952
* https://meta.trac.wordpress.org/changeset/5841

README: add php requires header

---

wpseo-news.php

As this is a premium plugin and not on GlotPress, the `Domain Path` tag should be set.

Main file: add missing `Domain Path` tag

---

.travis.yml
composer.json

* _N/A_
* Validate the `composer.json` file in low + high PHP/Composer combis
* Cache the correct Composer directories
**[Edit]**: I only noticed the builds failing after I had pulled the range of PRs - I've now added an additional commit to this PR to fix the PHP 7.2 unit test build.

Travis: few tweaks

---

classes/class-beacon-setting.php

_N/A_
Code directly after a `return` cannot be executed.
_N/A_

CS/QA: remove superfluous `break` statements

---

classes/class-head.php
classes/class-meta-keywords.php
classes/class-sitemap-editors-pick.php
classes/class-wpseo-news.php

_N/A_
Whenever a variable/function call output is compared to a string, one should *always* use a strict comparison as otherwise the results will become unpredictable.
If the value of the variable is a boolean, the hard-coded string will be cast to boolean before comparing, if the value of the variable is an integer, the string will be cast to integer, etc.
So when the variable is expected to be a string and a comparison is made against a hard-coded string, this should always be a strict comparison.
_N/A_

CS/QA: use strict comparisons when comparing strings

---

classes/class-admin-page.php
classes/class-meta-box.php
classes/class-sitemap-item.php
classes/class-sitemap.php

_N/A_
Strict type comparisons should be used as a rule, with loose type comparisons being the exception.
For array functions which do loose type comparisons, setting the third `$strict` parameter to `false` can be seen as a clear indication that this is a conscious, well thought out decision by the developer.
In all other cases, `$strict` `true` should be used.
For the ones addressed here, I've verified that they all do comparisons with strings, which is when it is most important to do a strict comparison (and also safe to change it to one).
_N/A_

CS/QA: Use strict comparisons with array functions

---

classes/class-wpseo-news.php

- Remove jQuery UI autocomplete from the enqueued scripts.
- Verify autocomplete wasn't used in this add-on, see also https://github.com/Yoast/wordpress-seo/pull/8875
Fixes #341

Don't enqueue jQuery autocomplete.

---

classes/class-wpseo-news.php

* Fixes a bug where Post was not enabled by default.
* Added a default option to parse when the argument is not set yet.
* Remove the `wpseo_news` option from your database
* Go to the News SEO settings and see `Post` being checked by default
Fixes #380

Set post enabled by default

---

.gitignore
grunt/config/aliases.yaml
grunt/config/compress.js
grunt/config/copy.js
package.json
yarn.lock

* Adds `copy:artifact` and `compress:artifact` command to Grunt to create an artifact zip.
* Using the grunt compress package
* Using the grunt copy package
* Adding a command that builds the project and creates a zipped artifact using the above named packages
1. Ensure you have all development dependency's for the project by running `yarn install`
2.  Execute the new command `create:artifact`, this is an alias that contains the following commands: 
* `update-version`
*  `build`
* `copy:artifact` 
* `compress:artifact`
The last 2 of this list are new commands
3. Check if the command does what is described below
`create:artifact: Create a zipped artifact from a fresh build` …

Added needed grunt commands to create a artifact 

---

classes/class-admin-page.php

While I understand that having this string in a variable is useful, there isn't any real need. It's not as if the variable is used in a lot of places throughout the code. Just few times directly following the old variable definition, so removing the variable was simplest.
Alternatively this block could be whitelisted, but that would open it up to new issues being introduced at a later stage.
Test this by checking that the `editors pick` section of the admin page still displays correctly as expected.

CS/XSS: remove need to escape output [5]

---

classes/class-wpseo-news.php
wpseo-news.php

* Settings page link was missing on the plugins page.
The `WPSEO_NEWS_FILE` constant is created for a reason: always having easy access to the filename of the "main" plugin file as registered with WP.
For the activation hooks, this is just a case of consistently using the constant.
For the second commit change - using `__FILE__` should cause WP not to recognize the plugin correctly and therefore not to display the settings link on the plugins page.
I haven't tested this, but I suspect this is currently not working and will start working again once this PR has been merged.
* (De-)Activating the plugin should still work as expected.
* The settings link for this plugin should now show up on the plugins page.

CS/QA: consistently use `WPSEO_NEWS_FILE` constant

---

classes/class-admin-page.php

All output should be escaped, including translations.
Includes minor code build up/layout changes.
* Open the NewsSEO admin page and verify that all elements on the admin page still display correctly.

CS/XSS: always escape output [4]

---

classes/class-meta-box.php

* _N/A_
This method falls through to the parent method if the parent exists - which it does since WPSEO `3.0`.
As we are a good two years down the road, this fall-back can be safely removed.
The method does not need to be deprecated as any function calls to it will fall through to the parent method, which is exactly as intended.
As a side-note: up to now, this method would have never fallen through to the parent as there is a typo in the `is_callable()` - `:` vs `::`.
* Verify that the metabox related functionality still works as expected. Most notably whether the metabox functionality shows up correctly on supported post types and does not on unsuppported post types.

CS/QA: remove superfluous fall-back function

---

classes/class-meta-box.php

All output should be escaped, including translations.
Simple non-controversial one. Use `esc_html()`, `esc_attr()` or `esc_url()` where appropriate.
This should not give any problems.
Test this by checking that the meta box header for `Google News` still displays correctly.

CS/XSS: always escape output [3]

---

classes/class-wpseo-news.php

*Checked for all functions that have been deprecated since before 4.0. Found one and removed it.  
* This PR cannot be tested specifically. It's a code cleanup and it should have no effect on the plugin. The only difference is that developers will not see warning messages anymore from functions that have been deprecated since before 4.0. The only way of testing is checking that the plugin still works. 
--> I have run the existing unittests and they don't throw any errors. 
Related [#8783](https://github.com/Yoast/wordpress-seo/issues/8783)

Cleanup: Removed deprecated functions from before 4.0.

---

classes/class-head.php

All output should be escaped, including translations.
Simple non-controversial ones. Use `esc_html()`, `esc_attr()` or `esc_url()` where appropriate.
These should not give any problems.
Test this by checking that the meta values of a news post are still added correctly to the header of the post on the front-end.

CS/XSS: always escape output [1]

---

tests/test-class-sitemap.php

*  _N/A_
Looks like one old/removed comment still made it back into the code base with the documentation fixes merge (vs the removal of the news keywords merge).
This removes it again.
* _N/A_

Clean up: Remove outdated comment/merge artifact

---

classes/class-sitemap.php
tests/test-class-sitemap.php

* Fixes a bug where older posts would be displayed in the sitemap despite them being older than 48 hours.
* Altered the query that retrieves the posts by calculating the difference in minutes instead of days. Because MySQL rounds off days / hours, it was possible to run into a situation where a post was 48 hours and 1 minute old, but would remain being queried due to said rounding of numbers. Using minutes means that anything older than `2880` minutes (48 hours) won't be retrieved.
**Please note that you still have to manually clear the cache. A new issue has been created regarding dealing with caches and expiration of news posts that will need to be addressed. See https://github.com/Yoast/wpseo-news/issues/396 for more …

Fixes old posts being queried for the News sitemap

---

grunt/config/makepot.js

If an artifact was build previously, this will be taken into account when re-generating the language files. Resulting in double entries which are not relevant.
* _N/A_
* Excluded the `optionally present` artifact folder from being parsed for translations.
* `grunt copy:artifact` - This generates an `artifact` folder in your local directory
* `grunt build:i18n` - This rebuilds the `pot` file
Fixes https://github.com/Yoast/wpseo-news/issues/406

Exclude artifact folder from POT file generation

---

classes/class-sitemap-images.php
tests/framework/class-wpseo-news-unit-test-case.php
tests/test-class-sitemap-images.php

* Fixes a bug where the news image sitemap did not correctly handle protocol relative URLs.
Commit summary:
If there is no functional reason to change the visibility of `private` methods to `protected`, it shouldn't be changed just to make the methods testable.
To still be able to test those methods in isolation, this helper method can be used.
Note: the helper method needs PHP 5.3.2+, which means that those methods can *not* be tested on PHP 5.2.
There were no unit tests yet at all for the `WPSEO_News_Sitemap_Images` class. This is a minimal start to add them. Related to #362.
The unit tests include a test for protocol relative URLs which will fail until the next commit is added.
With only a small code change relative URLs are …

WPSEO_News_Sitemap_Images::parse_image_source(): fix handling of protocol relative URLs

---

classes/class-head.php
classes/class-meta-box.php
classes/class-upgrade-manager.php

* Removes functionality for original-source as Google has confirmed they're no longer using it.
* Deleted all code that had to do with it, didn't deprecate because there's no need. There were no tests for this.
* Deleted the data that was no longer useful, also deleted the data for functionality that was removed in 7.7.
* Decided to _keep_ the meta news keywords fields, people might be using those for something else and it was editorially put in, so I don't really want to delete it without user consent.
* Go to News SEO settings on a post, see original source is gone.

Remove original source

---

classes/class-sitemap-item.php
classes/class-sitemap.php

* Fixes a bug where news posts set to no-index would still appear in the XML News Sitemap. 
* There are several settings to set a news post to no-index, in the database these are stored under `meta-robots-noindex'` for WPSEO and under `newssitemap-robots-index` for WPSEO News. The implementation is as such that if either of these two is set to no-index the post will not show in the news sitemap. 
* Activate the WPSEO News plugin, create a new post and open the sitemap. See that the post is in the News Sitemap. Set the post to no-index in one of 3 ways: 
-Set the individual post to no-index (in the settings under the post)
-Set all posts to no-index (under "Search Appearance" --> …

Added check to exclude no-index posts from news sitemap

---

classes/class-sitemap-item.php

* Fixes a bug where no-indexed items are shown in the sitemap
The next posts shouldn't visible on the news sitemap: 
* Create a post with `Exclude from News Sitemap` being checked. 
* Create a post with `Allow search engines to show this Post in search results?` set to `No`
* Set the default `Show Posts in search results?` for the content type `post` in SEO - Search Appearance - Post Types to `no` and create a post where you set `Allow search engines to show this Post in search results?` to default.
* Create  a post with `Googlebot-News index` set to `no-index`
Fixes #297

Do strict checks

---

assets/xml-news-sitemap.xsl
classes/class-sitemap-item.php
classes/class-sitemap-timezone.php
tests/assets/wpseo-news-sitemap-item-double.php
tests/test-class-sitemap-item.php

* Fixes a bug where the Publication Date in the News sitemap would be wrong when a hardcoded timezone was set (for example UTC + 2). 
* Class-sitemap-item now returns the UTC time by default in the news sitemap, if `post_date_gmt` is for the post. If not, it defaults to 'post_date' and returns the local time + timezone modifier. 
* Removed fallbacks relying on `post_modified` data, as this data is not available there and this always threw an error. 
* Removed code from 'class-sitemap-item' that attempted to guess the timezone, and replaced this with a conversion into a usable hard coded time string.   
**How to reproduce:** 
* Make sure the Yoast test helper is activated with …

Fixed a bug where the Publication Date in the News sitemap would be wrong

---

classes/class-wpseo-news.php

Fixes #422 
*  Prevents post type 'post' from being always on for News SEO.
* See #422, repeat those steps with and without patch.

 Prevents post type 'post' from being always on

---

classes/class-wpseo-news.php

Prevents post type 'post' from being always on for news seo

---

classes/class-admin-page.php
classes/class-sitemap-item.php
classes/class-upgrade-manager.php
tests/test-class-sitemap-item.php

* Allows term based exclusion in the news sitemap for all taxonomies connected to enabled post types.
* Moved the `catexclude_` options to a `term_exclude_<taxonomy>_<slug>_for_<post_type>` option for better portability.
* Make sure you have enabled at least one custom post type and one custom taxonomy. You can use the `Yoast Test Helper` for this.
* Go to the Yoast SEO News admin page.
* In the Yoast SEO News admin page enable at least one custom post type.
* Create a post and add one of those taxonomy terms you just selected.
* Create another post and do _not_ add one of those taxonomy terms you just selected.
* See only the second post in the XML news sitemap.
Be sure to also …

Add term exclusion for all taxonomies connected to enabled post types

---

composer.lock

Reverts Yoast/wpseo-news#443
This commit was created with an incorrect PHP version

Revert "Upgrade yoast/wp-helpscout to 2.0.4 in composer.lock"

---

classes/class-sitemap.php

* Fixes a bug where the last modified date for the sitemap index has been displayed with the wrong time zone 
* I've chosen to use UTC, because we are relying on the GMT date for the last modified date.
* Follow the steps from issue #435:
> Install Yoast News 8.3
> Set WordPress time zone to UTC
> Publish a post
> Compare the dates from the index and the newest post in the news sitemap. Correct UTC time on both index and news sitemap.
> Change WP time zone to something else.
> Disable/Enable the sitemap feature.
> Compare the dates from the index and the newest post in the news sitemap. Same date/time but the index still includes the time zone designator which makes it the wrong …

Use UTC for the sitemap index

---

grunt/config/aliases.yaml

* [not-userfacing] Added `grunt release` alias for consistency across projects.
*
* Run `grunt release`
Fixes #453

Added grunt release alias

---

classes/class-sitemap.php
tests/test-class-sitemap.php

* Fixes a bug where it was possible the 48 hour selection range for posts in the news sitemap was slightly off.  
* In the old scenario we checked posts comparing the post gmt time with NOW(), which returns the server time. This could result in errors when the server is not set to a GMT/UTC time zone. We now compare the post time zone with UTC_TIMESTAMP(). 
* This issue is very hard to test. Probably your test environment is set to UTC, so the result of NOW() and UTC_TIMESTAMP() are the same. 
* Testing the issue without touching the code but with patience:
-To reproduce the issue: 
-Create a post. Wait for 41 hours (maybe go get a cup of tea). Go to the news sitemap. See that the …

Compare time for news sitemap with UTC time instead of local server time. 

---

classes/class-sitemap.php

* Uses readfile instead of include in build_news_sitemap_xsl to prevent parsing xml file as PHP code.
* N/A
* Set `short_open_tag` to `on` in _php.ini_.
* Check _news-sitemap.xsl_ . It returns 500 error.
* Apply this PR and check _news-sitemap.xsl_ again. It should work without errors.
Fixes #247

Uses readfile instead of include in build_news_sitemap_xsl

---

classes/class-sitemap-item.php
tests/test-class-sitemap-item.php
tests/test-class-sitemap.php

* N/A
* Users might see the titles in their sitemap change because of this PR because it used to only show the post_title. Now it will show the SEO title, which when left untouched outputs the default settings for SEO title set under "Search Appearance", which in its turn defaults to post_title + site name when left untouched. 
* Added an extra test to cover the scenario where a default SEO title is set and where it is not. 
* Reproduce the steps in issue #459 
* Check out this branch.
* See it is fixed :)
* You can set the SEO title for a post in the "SEO title" field in the metabox (under 'edit snippet').
* The hierarchy should now function as follows: 
1) If a specific SEO title …

Fixes issue where the default SEO title was not shown in news-sitemap. 

---

classes/class-wpseo-news.php
tests/test-class-wpseo-news.php

* [not for changelog] Sets the minimum required WordPress version to 5.0.
* Sets the minimum required Yoast SEO version to 10.1.
* N/A
* Install this branch on a WP site with a version below 5.0. See a notification.
* Install this branch on an installation with a Yoast SEO version lower than 10.1. See a notification.
* Install this branch on a WP site with a version >=5.0 and Yoast SEO version >= 10.1. See no notifications.
Fixes [Yoast/wordpress-seo#12331](https://github.com/Yoast/wordpress-seo/issues/12331)

Set minimum required WP version to 5.0 and minumum yoast seo version to 10.1

---

tests/test-class-sitemap-item.php

* _N/A_
Variable names should be in `snake_case`.
Note: Local variable names can be safely changed to comply with this rule without breaking anything.
* _N/A_

CS: Rename non-snakecase variable

---

classes/class-sitemap.php

CS/QA: use `self` when referencing a (static) class member from within the same class

---

classes/class-wpseo-news.php
tests/test-class-sitemap.php

* _N/A_
WPCS 1.1.0 introduced a stricter check on function call layouts.
Multi-line function calls now need to have each argument on a new line.
See:
* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/1.1.0
* WordPress-Coding-Standards/WordPress-Coding-Standards#1330
This commit addresses multi-line function calls where parameters did not each start on a new line (and sometimes didn't need to either).
* _N/A_

CS: Each parameter should start on a new line in multi-line function calls

---

classes/class-wpseo-news.php
tests/test-class-sitemap-item.php
tests/test-class-sitemap.php

* _N/A_
WPCS 1.1.0 introduced a stricter check on function call layouts.
Multi-line function calls now need to have each argument on a new line.
In a next iteration of this principle, it is expected that a sniff will be introduced to ban multi-line function call arguments.
See:
* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/1.1.0
* WordPress-Coding-Standards/WordPress-Coding-Standards#1330
With this mind, function calls with multi-line parameters which are currently already causing errors to be thrown by PHPCS after the changes in WPCS 1.1.0, have been fixed - depending on the existing code - by:
* either changing multi-line function call …

 CS: Move multi-line parameters out of function calls

---

.travis.yml

* _N/A_
While the plugin has a minimum WP version of 5.0, Travis was still testing against 4.8./4.9.
See: https://github.com/Yoast/wpseo-news/blob/trunk/classes/class-wpseo-news.php#L107
* Check the Travis build output.

Travis: test against current WP versions

---

tests/test-class-sitemap-images.php
tests/test-class-wpseo-news.php

* _N/A_
`@covers` tags are used to indicate what class/method/function a test covers when calculating code coverage of the tests and should follow the specifications of PHPUnit.
Ref:
* https://phpunit.de/manual/6.5/en/appendixes.annotations.html#appendixes.annotations.covers
* https://github.com/Yoast/yoastcs/issues/123
* _N/A_

Test documentation: fix @covers tags

---

classes/class-sitemap-images.php

* Fixed Sitemap image URLs to use href instead of guid to prevent relative URLs in the Sitemap.
* Relative image URLs in the Sitemap which are not interpreted correctly by google. Besides not SEO friendly.
* https://github.com/Yoast/wpseo-news/issues/438
Fixes #

Fixed Sitemap image URLs to use href instead of guid.

---

classes/class-schema.php
classes/class-wpseo-news.php

* Adds Schema.org `NewsArticle` markup to all post types that you've selected as News.
* Makes all post types selected in the backend output `Article`, subsequently changing that to `NewsArticle`.
* Create a post or page.
* Make sure the post type is selected in the News SEO settings.
* See the output contains `NewsArticle` schema.
Fixes #485
Fixes #179
Fixes #343

Add NewsArticle output to News post types

---

classes/class-meta-box.php

* _N/A_
Depending on server configuration, the `REQUEST_URI` for the `$_SERVER` superglobal _may_ not be available. This prevents an "Undefined index" notice if that would happen.
* _N/A_
As it's neigh impossible to fake server variables, this can not be tested manually. A unit test _could_ be added for this. but so far, this whole class is untested.

CS/QA: make sure $_SERVER array key is set before using it

---

tests/framework/unittestcase.php
tests/sitemap-item-test.php
tests/sitemap-test.php
tests/wpseo-news-test.php

* _N/A_
This is a long established best practice.
PHPUnit contains a variety of assertions and the ones available have been extended  hugely over the years.
To have the most reliable tests, the most specific assertion should be used.
This implements this for the News plugin, while keeping in mind that at this time, PHPUnit 3.x should still be supported.
Refs:
* https://phpunit.de/manual/4.8/en/appendixes.assertions.html
* https://phpunit.readthedocs.io/en/7.5/assertions.html#
Most notably, this changes calls to `assertEquals()` to `assertSame()`, where `assertEquals()` does a loose type comparison and `assertSame()` does a strict type comparison.
Refs:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assert …

QA: use the most specific PHPUnit assertion possible

---

tests/bootstrap.php

* _N/A_
WP will load the active plugins automatically, there is no need to require YoastSEO explicitly.
Do more rigorous checking whether the environment is correctly set up for the unit tests to be run and if not, show an instructive error message.
* See PR https://github.com/Yoast/wpseo-woocommerce/pull/371

QA: review test bootstrap file / show friendly errors

---

classes/excludable-taxonomies.php
classes/schema.php
classes/sitemap-item.php
classes/wpseo-news.php
tests/doubles/schema-double.php
tests/schema-test.php

* Fixes a bug where the `@type` in the schema output would be `NewsArticle` instead of `Article` for articles which are excluded from the news sitemap.
* Moved the term exclusion functions to keep the code DRY.
* Added a protected function around `get_post` to be able to mock it in the tests.
* Go to the news settings and make sure you have a couple of post types turned on.
* Create a new post (or any/all of the activated above) and publish it.
* Go to the frontend of that post and check the schema output (tip: [GSDTT](https://search.google.com/structured-data/testing-tool)); it should have the `@type` of `NewsArticle`.
* Go to your news sitemap, the newly created post should be in …

Exclude from news sitemap schema fallback

---

grunt/config/copy.js

* Makes sure we don't copy files we don't need in the zip. 
* When I compared the zip that was build before https://github.com/Yoast/Wiki/pull/90, and the one with https://github.com/Yoast/Wiki/pull/90, I noticed some differences. This PR removes the files that were never included in the zip, but would otherwise be included after https://github.com/Yoast/Wiki/pull/90.
* See https://github.com/Yoast/Wiki/pull/90

Don't copy files we don't need in the zip

---

tests/bootstrap.php

* _N/A_
`opcache_reset()` is a PHP function, not a class.
Ref: https://www.php.net/manual/en/function.opcache-reset.php
* _N/A_ This change only affects the test bootstrap.

Bug fix: use the correct function

---

classes/sitemap-images.php
classes/sitemap-item.php
classes/sitemap.php
integration-tests/sitemap-test.php

* _N/A_
(well, unless anyone ever reported a bug about this, but chances of that are small as it would only really come into play when using UTF-8 characters in the images titles and captions in combination with PHP < 5.4)
From the PHP 5.4 changelogs:
> The default character set for htmlspecialchars() and htmlentities() is now UTF-8, instead of ISO-8859-1.
While _most_ of the WP world uses the WP default `utf-8` character encoding, this can be changed, so to be on the safe side, one should always pass the encoding to functions affected by it.
Refs:
* https://www.php.net/manual/en/migration54.other.php
* https://www.php.net/manual/en/function.htmlentities.php#refsect1-function.htmlentities-changelog
* …

 PHPCompatibility fix: pass encoding to htmlspecialchars() et al functions

---

integration-tests/sitemap-item-test.php
integration-tests/sitemap-test.php

* _N/A_
> WordPress core sets PHP time zone to UTC during boot. However it cannot guarantee that timezone isn't changed by third party code, which is relatively common in the wild.
>
> date() calls rely on current PHP time zone. If time zone is changed from UTC it causes invalid results through the core and extensions code.
Refs:
* https://core.trac.wordpress.org/ticket/46438
* https://github.com/WordPress/WordPress-Coding-Standards/issues/1713
Note: WPCS 2.2.0 (not yet released) will contain a check for the use of `date()`.
* _N/A_ These changes only affect unit test files, so as long as those still pass, we should be good.

QA: use gmdate() instead of date()

---

.travis.yml

* _N/A_
Remove redundant, duplicate `composer install`.
The `script` will use the Travis provided PHPUnit version when compatible and use the Composer installed one when not.
See: https://github.com/Yoast/wpseo-news/blob/af1ebddf58a4f568e46e9258549fbcc1609cc7eb/.travis.yml#L176-L197
The preceding `composer install` already takes this into account.
See: https://github.com/Yoast/wpseo-news/blob/af1ebddf58a4f568e46e9258549fbcc1609cc7eb/.travis.yml#L82-L88
So, there is no need to run a second `composer install` based on the unit test ENV variables.
* _N/A_
This is a build-script-only change and should have no effect on the functionality.

Travis: minor clean up

---

classes/admin-page.php

* _N/A_
Post type and taxonomy labels should never contain HTML, so can safely be escaped with `esc_html()`.
To that end, move the `esc_html()` from inside the `sprintf()` to wrapping the `sprintf()`.
* _N/A_
This is a code-only change and should have no effect on the functionality. Well, that is, unless someone would happen to add HTML to the post type/taxonomy labels, in that case, the display will now be different.

CS/QA: improve output escaping

---

tests/testcase.php

* _N/A_
As these new tests will only be run on PHP 5.6+ in combination with PHPUnit 5.4+, use the newer namespaced PHPUnit class name.
A class alias for BC is not needed as BrainMonkey is not available on PHP < 5.6, so older PHPUnit versions do not need to be supported.
* _N/A_ If the unit tests are still being run and pass, we're good.

PHPUnit: make (new) unit tests compatible with higher PHPUnit versions

---

integration-tests/bootstrap.php

* _N/A_
Probably changed when a blanket search/replace was done for `/tests/`, but this is not the WPSEO News `tests` directory, but the WP Core ` tests` directory which is being referred to.
Related to and a prerequisite for #553
* _N/A_
This should fix a small part of the build failures, but cannot easily be tested stand alone.

Tests: fix path to WP native bootstrap

---

integration-tests/schema-test.php

* _N/A_
This test has been failing for a while - since commit 460da5aa4903f831ca3ab0659708516ae48ba594 - and the failure was hidden by errors in the Travis script.
The change made in the above mentioned commit means that the URL for `copyrightHolder` will always have a trailing slash before the hash `#`.
The unit tests were not updated for this change, causing them to fail.
Related to and a prerequisite for #553
* Run the integration tests locally against a high PHP version in combination with `trunk` and see them fail.
* Switch to this branch and see the unit tests passing.

Schema: fix failing test

---

integration-tests/sitemap-item-test.php
integration-tests/sitemap-test.php

* _N/A_
These two tests both use the `DateTimeZone` class combined with the output of the `WPSEO_News_Sitemap_Timezone::wp_get_timezone_string()` method.
This method _may_ return the timezone as an UTC-offset, but the PHP `DateTimeZone` class did not support timezone offsets as input until PHP 5.5.10.
As support for PHP < 5.6 is about to be dropped, for now, let's just skip these tests on low PHP versions.
Ref: https://www.php.net/manual/en/datetimezone.construct.php#refsect1-datetimezone.construct-changelog
Related to and a prerequisite for #553
* Set your local environment to a PHP version < PHP 5.5.10.
* Switch WP to WP 5.1.
* Switch to a PHPUnit version which will run with that …

Tests: mark two tests for skipping on low PHP versions

---

.travis.yml

* _N/A_
Some of the build failures are due to the test double classes not being found when they are supposed to be auto-loaded.
```
Fatal error: Class 'WPSEO_News_Sitemap_Item_Double' not found in /tmp/wordpress/src/wp-content/plugins/wpseo-news/integration-tests/sitemap-item-test.php on line 34
```
The problem here is that the `composer.json` contains an `autoload` `classmap` directive as well as an `autoload-dev` `classmap`.
In the Travis script, the `composer install` command is run with `--no-dev` on PHP < 7.2.
That means that for those PHP versions, the classmap generated did not contain the test classes, leading to the above mentioned kind of failures.
So, while using the Travis standard PHPUnit version in combination with …

Tests: fix test double classes not being found

---

.travis.yml

* _N/A_
The Travis builds have been failing for quite a long time, but due to the script being set up incorrectly, this has gone (nearly) unnoticed.
The main problems were:
* Incorrect indentation.
* Incorrect folding.
* Commands where the exit code should determine build pass/fail being nested.
Travis does not handle nested conditions well.
The above has all been cleaned up and the build is now correctly failing on all builds which run unit tests.
In addition to this:
* Removing `sudo`.
Travis has not supported `sudo` for quite a while.
* Moving the merging of the code coverage test output to the `after_script` section.
**IMPORTANT NOTE**:
**The build for this PR will not pass until all the failing unit tests have been fixed and …

Travis: fix broken script

---

.travis.yml
composer.json
composer.lock
integration-tests/bootstrap.php
wpseo-news.php

* _N/A_
> ~~This PR requires PR #553 to be merged first~~
> ~~Once that PR has been merged, I will rebase this PR and change it from Draft to Mergable.~~
Brief analysis of the Travis script shows me that:
* There are a number of builds _which do not do anything_.
All the tasks in `script` are set up conditionally based on environment variables.
- Any build which did not have an environment variable, such as `PHPLINT`, `PHPCS` or `PHPUNIT` is basically completely useless, i.e the `PHP 7.3 WP_VERSION=master` build.
* There are three different environment variables related to toggles for running the unit tests:
- `PHPUNIT` - to run the new BrainMonkey based tests.
- `PHPUNIT_INTEGRATION` - to run the old integration tests.
- …

Stop explicit support for PHP < 5.6 / WP < 5.2

---

classes/sitemap-item.php
integration-tests/sitemap-item-test.php
integration-tests/sitemap-test.php

* Use the post title instead of the SEO title, this is based on the specs for the news sitemap.
*
* Add a new post
* Open the news sitemap and verify that the title is the post title and not the seo title.
Fixes #

Remove the usage of the seo title

---

classes/wpseo-news.php

Enable usage tracking.
*  None needed.
* Site should send tracking info if this plugin is enabled icw Yoast SEO free.

Enable usage tracking

---

classes/schema.php

* Fixes a bug where the time in the `copyrightYear` schema output could be incorrect.
*
* Create a new post and view the source of the frontend.
* Search the schema output `NewsArticle` piece.
* Verify the `copyrightYear` still has the UTC / GMT time with `+00:00` included.
Fixes https://github.com/Yoast/wordpress-seo/issues/13906

Use date helper

---

.travis.yml

* _N/A_
Includes:
* Adjusting the Travis matrix now WP 5.3 has been released
* Removing the build against PHP 7.4 from `allowed failures`.
* Adding (back) a build against PHP `nightly` (PHP 8) and adding it to  `allowed_failures`.
For now, this build will only lint the code. Unit testing is not yet possible with  the current setup.
* Check the detailed output of the Travis script

Travis: don't allow builds against PHP 7.4 to fail

---

classes/sitemap.php

* Fixes a bug where the sitemap could be invalidated twice on multisite with MultilingualPress.
*
These are kind of hard to test. The idea is that the code could get called twice when on multisite.
Therefore, some debugging is needed to verify this. [See this Wiki page to learn how](https://github.com/Yoast/Wiki/wiki/PHPStorm-debugging).
*Note: To acquire a copy of MultilingualPress, login to LastPass -> Shared-licenses vault. There's a login there for MultilingualPress so you can download the latest version.*
These are kind of hard to test. The idea is that the code could get called twice when on multisite.
Therefore, some debugging is needed to verify this. [See this Wiki page to …

Add missing multisite checks for the actions

---

classes/admin-page.php
classes/sitemap-item.php
classes/sitemap-timezone.php
classes/sitemap.php
classes/upgrade-manager.php
integration-tests/sitemap-item-test.php
integration-tests/sitemap-test.php

* Show dates in UTC+0 format everywhere.
* Removal of the timezone notice, because we now always rely on the UTC+0 time.
* Make sure no notice will be shown when setting timezone settings to a utc + somewhat value.
* Make sure the right date (UTC time +00:00) is shown in the sitemaps:
* test with a location-based timezone
* test with a +number timezone (e.g. +02:00)
* test the upgrade routine
Related: https://github.com/Yoast/wordpress-seo/issues/13906

Implement date helper

---

package.json
yarn.lock

Bump plugin-grunt-tasks to v1.6
* None needed.
* No changes to `aliases.yaml` needed in this one.
* Make sure `build` task remains working.

Bump plugin-grunt-tasks

---

classes/sitemap-timezone.php

* _N/A_
**Note**: while this is a bugfix, the bug has not been in a released version yet, so this is non-user-facing.
The constant `__METHOD` does not exist. The magic PHP constant `__METHOD__` does.
Ref: https://www.php.net/manual/en/language.constants.predefined.php
Using a non-existent constant will cause PHP < 8 to thrown a warning + then treat the constant as a string.
In this case, that means that the deprecation warning would not list the method name of the deprecated method, but would say something like `__METHOD is deprecated since version ...`.
* Make sure `WP_DEBUG` is on / PHP `error_reporting` is set to `-1`.
* Add a code snippet in a custom plugin/theme `functions.php` …

Bugfix: use the magic constant

---

classes/meta-box.php

* _N/A_
* WP slashes all superglobals, so before actually using a index, it should be unslashed.
* Before doing a compare, sanitize the text string to clean it off null bytes and invalid UTF-8.
* ... good question....

QA: sanitize use of a superglobal

---

classes/admin-page.php
classes/excludable-taxonomies.php
classes/meta-box.php
classes/option-news.php
classes/option.php
classes/schema.php
classes/sitemap-images.php
classes/sitemap-item.php
classes/sitemap.php
classes/upgrade-manager.php
classes/wpseo-news.php
integration-tests/schema-test.php
integration-tests/sitemap-images-test.php
integration-tests/sitemap-item-test.php
integration-tests/sitemap-test.php

* N/A - Integratie with the WPSEO Options framework.
*
* Checkout `master` and make some settings on the News SEO page. Set a name, a default genre, include a post type, save it and then select some terms to exclude and save it again.
* Go to your database and copy in the table `wp_options` the option value for `wpseo_news`
* Checkout this `release/12.4` 
* Open the news settings and verify the settings are there. 
* Save the settings and see all fields are empty.
* To be sure set the copied option value in the database.
* Checkout this branch
* Go the the settings page for news. All fields should be filled.
* Save it and verify all fields keeps filled.
* Go to your news sitemap and …

Integration with the WPSEO Options framework.

---

classes/wpseo-news.php

* N/A - Fixes a regression where not all options are saved
*
* Enable woocommerce
* Go to the news settings page
* Enable the products post type and save
* Verify that the checkbox is still checked
https://github.com/Yoast/wordpress-seo/issues/14141

Change the hook priority

---

classes/admin-page.php
classes/option.php
classes/upgrade-manager.php
classes/wpseo-news.php
tests/doubles/option-double.php
tests/news-test.php
tests/option-test.php

* Fixes a bug where pages are loaded slowly
* Followed everything mentioned in this comment https://github.com/Yoast/bugreports/issues/822#issuecomment-573637790, except for the test for `is_excluded_through_terms` because that is too complex with static dependencies.
* Makes sure the upgrade routine has ran successful, please set that version constant `WPSEO_NEWS_VERSION` to 12.4.1-RC1
* Use the settings for news and set the post type to exclude and verify the post is excluded
* Do the same for the terms.
* Test the performance on a site with many tags. See https://github.com/Yoast/bugreports/issues/822
Fixes https://github.com/Yoast/bugreports/issues/822
Fixes #592

Fixes the performance

---

.phpcs.xml.dist
classes/admin-page.php
classes/wpseo-news.php
tests/doubles/option-double.php
tests/news-test.php
tests/option-test.php

* N/A
* The `trunk` build on Travis was failing. I've fixed all errors/warnings, except the following errors/warnings in `tests/doubles/option-double.php`:
```
FILE: tests/doubles/option-double.php
----------------------------------------------------------------------
FOUND 5 ERRORS AND 2 WARNINGS AFFECTING 4 LINES
----------------------------------------------------------------------
8 | ERROR   | Double/Mock test helper classes should be placed in a
|         | dedicated test doubles sub-directory. Found class:
|         | Option_Double
|         | (Yoast.Files.TestDoubles.WrongDirectory)
13 | WARNING | Possible useless method overriding detected
|         | (Generic.CodeAnalysis.UselessOverridingMethod.Found)
17 | ERROR   | …
```

Fix various CS errors and warnings

---

integration-tests/bootstrap.php
wpseo-news.php

* _N/A_
Minor code simplification which is possible now PHP 5.6 is the minimum version.
Ref: https://www.php.net/manual/en/language.constants.predefined.php
* _N/A_

Modernize: use `__DIR__` instead of `dirname( __FILE__ )`

---

integration-tests/admin-page-test.php

* _N/A_
Nowdoc (PHP 5.3+) equates to heredoc as single quoted strings to double quoted strings: no variable interpolation will be done.
As the text string in the heredoc did not contain any variables, nowdoc is the more appropriate construct to use for this text snippet.
Ref: https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc
* _N/A_

Modernize: use nowdoc instead of heredoc

---

integration-tests/admin-page-test.php

* _N/A_
The variable `$wpseo_admin_page` did not exist and would therefore always be empty.
* _N/A_
This is a test-only change. If the tests still pass, we're good.

Integration tests: bug fix / typo

---

classes/sitemap-item.php
classes/sitemap.php

* _N/A_
Lower memory usage by not assigning to a variable when all that's being done is return the same.
* _N/A_

QA: remove useless variables

---

tests/doubles/option-double.php
tests/news-test.php
tests/option-test.php
tests/testcase.php

* _N/A_
Always be explicit about which classes are being used in a namespaced file, even when it's a class from within the same namespace.
* _N/A_

QA: add missing `use` statements

---

tests/testcase.php

QA: declare static closures as static

---

integration-tests/sitemap-test.php

* _N/A_
This variable is not used anywhere, so no need to assign the return of the function call to a variable.
* _N/A_

QA: remove redundant variable assignment

---

tests/news-test.php

* _N/A_
This code is not used during the test and was probably copy/pasted to the file to check what tests should be created for this function (which is part of the plugin).
It is dead code and should be removed.
* _N/A_
This is a test-only change. If the tests still pass, we're good.

Tests: remove WIP copy/paste code

---

classes/excludable-taxonomies.php
classes/head.php
classes/javascript-strings.php
classes/meta-box.php
classes/schema.php
classes/sitemap-images.php
classes/sitemap-item.php
classes/sitemap.php
classes/upgrade-manager.php
classes/wpseo-news.php
integration-tests/doubles/sitemap-item-double.php
integration-tests/doubles/wpseo-news-double.php
integration-tests/framework/unittestcase.php
integration-tests/sitemap-item-test.php
integration-tests/sitemap-test.php
integration-tests/wpseo-news-test.php
tests/option-test.php

* _N/A_
No need to annotate minimum PHP version when it's below PHP 5.6, now that's the minimum version.
The function parameter can also be `null` (default).
The function returns an explicit `null` in certain circumstances, so this should be documented as a valid return type.
PHP has no concept of named return variables, so the name of the variable has no value in the `@return` tag.
`void` means the function returns nothing. This type cannot be combined with other types. It is an absolute.
If a function returns either something or nothing, this should be documented as `type|null` and functions calling this function should check the return value for type.
* _N/A_
This is a …

Docs: various fixes

---

.phpcs.xml.dist
classes/admin-page.php
classes/excludable-taxonomies.php
classes/head.php
classes/javascript-strings.php
classes/meta-box.php
classes/option.php
classes/schema.php
classes/sitemap-images.php
classes/sitemap.php
classes/upgrade-manager.php
classes/wpseo-news.php
composer.json
composer.lock
integration-tests/bootstrap.php
integration-tests/framework/unittestcase.php
integration-tests/meta-box-test.php
integration-tests/schema-test.php
integration-tests/sitemap-images-test.php
integration-tests/sitemap-item-test.php
integration-tests/sitemap-test.php
integration-tests/wpseo-news-test.php
wpseo-news.php

* This deprecates  the `wpseo_news_head` action hook in favour of the `Yoast\WP\News\head` hook.
* This deprecates  the `wpseo_news_head_display_noindex` filter hook in favour of the `Yoast\WP\News\head_display_noindex` hook.
* This deprecates  the `wpseo_news_sitemap_name` filter hook in favour of the `Yoast\WP\News\sitemap_name` hook.
This updates the dependency in `composer.json`, as well as the PHPCS ruleset for YoastCS 2.0.0.
Includes:
* A selective update of the `composer.lock` for just YoastCS and its dependencies.
* Removing the tweaks to the Composer `check-cs` script to change the minimum required PHP version.
As of YoastCS 2.0, PHP 5.6 is now the default minimum PHP version.
Ref: …

PHPCS: Update to YoastCS 2.0.0

---

classes/googlebot-news-presenter.php
tests/googlebot-news-presenter-test.php
tests/news-test.php

* There are changes made in the abstract interface (https://github.com/Yoast/wordpress-seo/pull/14706). This allows us to extend that interface, but it also needs a couple of change to make it work 100%.
* N/A - It's a logic wise change.
*
* Make sure the noindex tag is still outputted. 
* It should be rendered between the debug markers.
Fixes #

Adapts the presenter interface changed made in Yoast SEO

---

tests/googlebot-news-presenter-test.php
tests/news-test.php
tests/option-test.php

Import `use` statements for classes in the same namespace will not be allowed.
* _N/A_

CS: no `use` statements for same namespace

---

classes/wpseo-news.php
integration-tests/admin-page-test.php
integration-tests/sitemap-images-test.php
integration-tests/sitemap-test.php
tests/googlebot-news-presenter-test.php
tests/option-test.php

Use unqualified names instead.
If the file is namespaced and the docblock comment involves a class from another namespace and no `use` statement is in place yet, add an import `use` statement.
Note: PHPUnit `@covers` tags *should* still be fully qualified (PHPUnit requirement)
* _N/A_

CS: don't use FQN in docblocks

---

classes/googlebot-news-presenter.php

*
* Makes sure Yoast SEO News is compatible with the latest Yoast SEO.
* Added a `get` function to `WPSEO_News_Googlebot_News_Presenter` to make it compatible with `Abstract_Indexable_Presenter`.
* Create a new post.
* Make sure the editor doesn't crash.
* In the metabox, set `Google News` -> `Googlebot-News index` to `noindex`.
* Publish the post, and on the front end make sure the `Googlebot-News` meta value is set to `noindex`.
Fixes #

Added get method to WPSEO_News_Googlebot_News_Presenter

---

.gitignore
Gruntfile.js
assets/admin-page.min.js
classes/meta-box.php
classes/wpseo-news.php
css/src/admin-metabox.scss
grunt/config/aliases.yaml
grunt/config/clean.js
grunt/config/copy.js
integration-tests/meta-box-test.php
package.json
yarn.lock

* This pull relies on [this pull](https://github.com/Yoast/wordpress-seo/pull/15550/files) being merged into Yoast SEO.
* Plugin no longer loads its own CSS file.
* Added one CSS class to the new admin styling classes, dropped the CSS file from this plugin.
* Update, see the Yoast meta box -> News SEO  content looks good.

Bump plugin-grunt-tasks, remove CSS

---

.travis.yml

* We want to make sure that the dependency injection container of WordPress SEO can be loaded when running the Travis builds.
* Fixes a bug where the dependency injection container of WordPress SEO could not be installed in the Travis build when cloning and installing WordPress SEO.
* Instead of the normal development repository, the distribution version of WordPress SEO is now cloned and installed.
* This means that the dependency injection container is already created and can be used out of the box.
* Check the Travis build. It should pass with flying (e.g. green) colors.
Fixes #

Distribution version of WordPress SEO is now loaded.

---

.travis.yml
README.md
integration-tests/wpseo-news-test.php

* On August 11, WordPress 5.5 will be released. Because we always support the 2 latest versions, the minimum supported version needs to be updated to 5.4.
* Set minimum supported WordPress version to 5.4.
*
*
Fixes #

Set minimum WP version to 5.4 and tested up to to 5.5

---

wpseo-news.php

*
* Enables tracking when activating the plugin. It can be disabled in the Yoast SEO configuration wizard.
*
* Make sure that the plugin is deactivated.
* Make sure that you have tracking disabled.
* You can do this in the Yoast SEO configuration wizard.
* Go to the Yoast SEO admin dashboard (click on _SEO_ in the admin sidebar menu).
* Click on the link titled _reopen the configuration wizard_.
* Open step 7 (_Help us improve Yoast SEO_).
* Select _No, I don't want to allow you to track my site data_.
* In your site's database, check the `wpseo` option in the `wp-options` table.
* Its `tracking` parameter in the serialized `option_value` should be set to `0` (no tracking).
* [You …

Enables tracking on plugin activation.

---

classes/schema.php
integration-tests/schema-test.php

* WPSEO News should output `NewsArticle` for all posts / pages / terms where it is enabled.
* Fixes a bug where the schema article type would be overwritten instead of added to.
* We need to check whether the types object is an array, if not, we convert it to one and add `NewsArticle` to it.
* Install latest WordPress SEO and WPSEO News
* Enable WPSEO News
* Make sure that you have a valid `Knowledge graph & Schema.org` section.
* Enable News SEO for the type you want to test (i.e. Pages)
* Make sure that the output contains `NewsArticle`.
* If you overwrite the default Article Type (`Article`) with something else (i.e. `ScholaryArticle`) the output should contain an array with …

P1 113 Page does not output NewsArticle

---

wpseo-news.php

*
* Fixes a bug where a fatal error would be thrown when News SEO would be activated when Yoast SEO (Premium) was not activated.
*
* Deactivate News SEO
* Deactivate Yoast SEO (premium)
* Activate News SEO
* See no fatal error
* Check that tracking is still activated.
Fixes https://yoast.atlassian.net/browse/QAK-2167

[QAK-2167] Check if WPSEO_Options exists before calling one of its methods

---

.phpcs.xml.dist
composer.json
config/composer/actions.php

* Introduces the `composer cs` command; as also present in Yoast SEO
* Tooling: introduces the `composer cs` command
* Adjusted CS configuration to handle the config folder; inspired on Yoast SEO
* Created a config directory
* Removed the `yoast-configcs` command; which is no longer needed
* Run `composer install`
* Run `composer cs` and get a menu to pick which check you want to perform
* Perform any of the menu options and see them working as expected
Fixes #

Introduce `composer cs` command

---

composer.json
composer.lock

* Update test dependencies
* Update test dependencies
.. to prevent dependencies being locked at a version incompatible with PHP 5.6 due to a Composer command having been run on a higher PHP version.
Updated:
* BrainMonkey from v 2.4.0 to 2.5.0.
Note: this version contains a test breaking change, which doesn't impact this repo.
* Mockery from v 1.3.0 to 1.3.3.
Improved support for PHP 8.
* Hamcrest-php from v 2.0.0 to 2.0.1
... which claims compatibility with PHP 8.
* Patchwork from v 2.1.11 to 2.1.12
This fixes [two issues](antecedent/patchwork#99) which _might_ be relevant for us.
Refs:
* https://github.com/Brain-WP/BrainMonkey/releases
* https://github.com/mockery/mockery/releases
* …

Composer: update BrainMonkey and dependencies

---

classes/schema.php
composer.json
composer.lock
tests/doubles/option-double.php

* Updated dev dependencies
* Updated dev dependencies
* Updated YoastCS from `2.0.2` to `2.1.0`.
* Updated PHP_CodeSniffer from `3.5.5` to `3.5.8`.
* Updated the DealerDirect Composer plugin from `0.6.2` to `0.7.0` (which is  compatible with Composer 2.0).
Relevant changes in YoastCS:
* The minimum supported WP version has changed to `5.4`.
* A new check for test doubles being named as such.
* A few bugfixes.
* Various sniffs now provide metrics.
Relevant changes in PHPCS:
* PHPCS will now _run_ without problems on PHP 8.
Note: it will not necessarily handle all code using PHP 8 syntax correctly  yet, though it does contain preliminary support for various syntaxes.
* Lots of bugfixes.
Refs:
* …

Composer: update YoastCS to v 2.1.0

---

.gitignore
.travis.yml
composer.json
composer.lock
phpunit.xml.dist
tests/bootstrap.php
tests/googlebot-news-presenter-test.php
tests/option-test.php
tests/testcase.php

* Preparation for compatibility with PHP 8
* Preparation for compatibility with PHP 8
* Adds a dev dependency to the `yoast/wp-test-utils` package, which will also  make the PHPUnit Polyfills available.
* As that package already requires and manages the installable versions for  BrainMonkey and PHPUnit, remove these as explicit requirements from `require- dev` in favour of letting the WP Test Utils package manage the versions.
The install is done based on PHP 5.6 and includes updating the dependencies  from PHPUnit itself within the constraints of maintaining compatibility with  PHP 5.6.
This new package adds the following features:
* Polyfills for various PHPUnit cross-version changes.
* Basic test cases for use by the plugins. …

Unit Tests: make the testsuite compatible with PHPUnit 9 and test against PHP 8

---

.travis.yml
composer.json
composer.lock
integration-tests/admin-page-test.php
integration-tests/bootstrap.php
integration-tests/framework/unittestcase.php
integration-tests/sitemap-test.php
phpunit-integration.xml.dist

* (Preparation for) compatibility with PHP 8
* (Preparation for) compatibility with PHP 8
:bulb: This PR will be easiest to review by going through the individual commits one by one.
A new version of the WP Test Utils package has been released which deals with the necessary work-arounds for the WP integration tests and adds utilities for this which individual plugins can use, like functions for the bootstrap and a `TestCase` which includes all the polyfills from the PHPUnit Polyfill repo.
The install is done based on PHP 5.6 (`config.platform.php` is set in the `composer.json` file).
Refs:
* https://github.com/Yoast/wp-test-utils/releases/tag/0.2.0
This switches the parent class of the `WPSEO_News_UnitTestCase` to the WP Test …

Integration Tests: make the testsuite x-version compatible and test against PHP 8

---

assets/xml-news-sitemap.xsl
classes/admin-page.php
classes/meta-box.php
classes/option.php
classes/sitemap-item.php
classes/upgrade-manager.php
classes/wpseo-news.php
yarn.lock

* Google made their news genre obsolete: https://twitter.com/jdevalk/status/1207608446931099649
* Removes the news genre from the News sitemap and settings.
* Remove genre from the: metabox, settings, sitemap and database.
* Deprecate `WPSEO_News::list_genres`.
* Switch to the _previous version_ of News SEO (devs: `trunk`).
* Go to the news settings: SEO -> News SEO
* Change the default genre to something.
* Ensure you have news enabled for a post type.
* Save the settings.
* Create a new post (or whatever the post type you enabled news for).
* Change the genre in the metabox news tab.
* Save the post.
* Check your database:
* `wp_options` table should have a `wpseo_news` …

P1-299 remove genre settings

---

classes/wpseo-news.php

* As some settings are changed in News SEO our users need to be informed. So we need to add a notification to the notification center for that.
* In this version changes are made to the settings. We added a notification to inform our users about those changes.
*
* With Yoast SEO or Yoast SEO Premium and News SEO active, a new notification should show up in the notification center
* Check that the notification is the same as in the design
* When an URL to the post about this changes has been given, make sure that the link points to that url instead of yoast.com
* With Yoast SEO or Yoast SEO Premium and Video SEO active, a new …

P1-300 Add notification for changes in News SEO

---

classes/admin-page.php
wpseo-news.php

* Prevent mixed content warnings, needless redirections and improve security.
* Fixes "mixed content" warnings on the News SEO options page.
* I changed the registration URL to point directly to the registration page.
* The `'glotpress_url'  => 'https://translate.yoast.com/gp/',` URL does not seem to be used. This URL itself goes to a 302 redirected page to `https://translate.yoast.com/gp/projects/`. I contemplated changing the complete URL like I did with the registration URL, but since I could not find it being used I did not see a direct impact by not changing this.
* All these URLs should probably get converted to `yoa.st` links at some point.
1. Change the language …

Convert visible URLs to https

---

classes/wpseo-news.php

* Notifications about the changes needed to be removed.
* Removes an unreleased notification from the notification center.
*
* Deactivate News SEO
* Remove the row `wp_yoast_notifications` from your `wp_usermeta` table in your database
* Update News SEO to this version
* Activate News SEO
* Make sure no notification about the changes is added to the notification center
*
*
Fixes P1-358

Removes the no longer wanted notification

---

classes/wpseo-news.php

* As a followup to https://github.com/Yoast/wordpress-seo/pull/16615 this switches the news plugin to a filter instead of loading the HelpScout class separately.
* Improve how we load HelpScout.
*
* The beacon should still load with this patch applied.
*
*
Fixes #

Improve how we load HelpScout

---

classes/sitemap-images.php

* We want to fix a failing integration test.
* Fixes failing integration test by updating a conditional check for get_post_thumbnail_id.
* WordPress 5.5. [changed the return value of get_post_thumbnail_id](https://core.trac.wordpress.org/changeset/48310) for non-existing posts from an empty string to `false`. Our code was still checking for empty string.
* Check the Travis build passes. The failing test was `WPSEO_News_Sitemap_Test->test_sitemap_NOT_empty()`.
N/A (just check the Travis build passes)
*
*
Fixes [P3-361]

P3-361 Update conditional check for get_post_thumbnail_id

---

classes/wpseo-news.php
integration-tests/wpseo-news-test.php

* We need to bump the minimal required version for WPSEO, because we're introducing a Dismissable alert that depends on WPSEO 16.0
* Sets the minimum required Yoast SEO version to 6.0.
*
* Check if activating the plugin with this branch and an older version of WPSEO than 16.0 will result in an upgrade notification
* Updating WPSEO should remove this notification and should allow News to function again
*
*
Fixes [P1-392](https://yoast.atlassian.net/browse/P1-392)

Bump minimal required WPSEO version

---

.babelrc
classes/admin-page.php
classes/integrations/editor-changes-alert.php
classes/meta-box.php
classes/sitemap-item.php
classes/upgrade-manager.php
classes/wpseo-news.php
config/webpack/externals.js
config/webpack/paths.js
config/webpack/webpack.config.js
integration-tests/meta-box-test.php
integration-tests/sitemap-test.php
js/src/components/Editor.js
js/src/components/Metabox.js
js/src/components/Sidebar.js
js/src/containers/EditorContainer.js
js/src/helpers/fields/EditorFields.js
js/src/initializers/initializeEditorPage.js
js/src/initializers/initializeSettingsPage.js
js/src/redux/actions/editor.js
js/src/redux/reducers/editor.js
js/src/redux/selectors/editor.js
js/src/yoast-seo-news-editor.js
js/src/yoast-seo-news-settings.js
package.json
yarn.lock

* Use React for the News tab in the editor.
* Add News to the sidebar in the block editor and in Elementor.
* Merge the `Exclude` and `Google News`'s (no)index options into one (the latter).
* Add News to the sidebar in the block editor and in Elementor.
* Changes News in the metabox.
* NON-USER-FACING Fixes an unreleased bug where a JS error would be shown on the settings pages when you have the debug flag on.
* Move hook calls from constructor to `register_hooks`, preventing immediate side effects.
* Now always registering extra meta fields. There was a post edit/new and sitemap check around this. The fields can always be registered for simplicity.
* I tried to DRY up the supported post type check, by putting it outside of the …

P1-301 reactify editor

---

classes/wpseo-news.php
tests/bootstrap.php

* See #660 for description of the issue
* Fixes a bug where certain conditions (e.g. using a different admin language) would result in an endless loop.
* The loop was caused by the querying of the options cache in functions called hooked to the WP `get_options`. The variables storying the options value were converted to static properties since they are accessed by static methods. This is not optimal, also for testing purposes.
* in `Settings` > `General`, install a different language from the default one. Then, switch back to the default language, but this way you will have the chance to select a different language for your user.
* In `Users` > `Profile`, change the …

P3-362 Move reading of options outside functions called by options cache priming, to avoid loops

---

classes/wpseo-news.php
integration-tests/wpseo-news-test.php

* We need to bump the minimal required version for WPSEO, because we're using the checkbox that is introduced in `@yoast/components` that is shipped with WPSEO 16.1
* Sets the minimum required Yoast SEO version to 16.1.
* Using `beta` instead of `RC` now
* Check if activating the plugin with this branch and an older version of WPSEO than 16.1 will result in an upgrade notification
* Updating WPSEO should remove this notification and should allow News to function again
*
*
Fixes https://yoast.atlassian.net/browse/P1-442

P1-442 Bump minimal required WPSEO version

---

classes/sitemap-item.php

* Some users have additional criteria to include/exclude items from the news sitemap. Therefore, we make the decision to include an item filterable.
* From joneslloyd: We have a requirement to skip all posts that _don't_ have a specific taxonomy term( "News"). Adding this filter would give us the ability to add our required functionality, and we'd therefore be able to purchase this add-on (otherwise we have to implement the same functionality in-house).
* Adds a filter to override the decision to omit an item from the news sitemap. Props to [joneslloyd](https://github.com/joneslloyd)
*
* In news-seo, go to the news settings and add posts to news sitemap.
* find the id of …

Allow filtering of decision to skip building sitemap item

---

classes/sitemap-item.php

We have a requirement to skip all posts that _don't_ have a specific taxonomy term( "News"). Adding this filter would give us the ability to add our required functionality, and we'd therefore be able to purchase this add-on (otherwise we have to implement the same functionality in-house).
changelog: enhancement
N/A(?)
Use the `Yoast\WP\News\skip_build_item` filter to exclude a CPT that has passed the other requirements for not being excluded. The two params are the current exclude status (`false`), and the item ID.
N/A
N/A
N/A
Fixes #

Add the ability to filter News Sitemap items for exclusion

---

classes/sitemap.php

* querying the same column twice is unnecessary but causes trouble in [systems that use Vitess](https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt#L115)
* removed a duplicate column selection
* removing a column that's queried twice doesn't affect results but DOES impact sql validation.
* view the sitemap. No side-effects or errors should be noticable.
*
*
Fixes #695

remove duplicate selection of `post_date_gmt`

---

classes/sitemap.php
integration-tests/sitemap-test.php

* Improve the sitemap query performance.
* Improves the performance of the news sitemap. Props to [archon810](https://github.com/archon810).
* Make sure you have a large selection of posts that have a valid post type for the news sitemap ( these are set in the settings ).
* This should include posts more than 2 days old ( these should not show in the sitemap ).
* The output of the news sitemap should be identical, with all valid items less than 2 days old appearing and valid items more than 2 days old not appearing.
* The news sitemap.
Fixes #690

Adjust sitemap query to improve performance

---

.travis.yml
classes/googlebot-news-presenter.php
classes/wpseo-news.php
composer.json
composer.lock
config/grunt/task-config/shell.js
integration-tests/wpseo-news-test.php
tests/googlebot-news-presenter-test.php
tests/testcase.php

* Made News compatible with new Abstract Indexable Tag Presenter in free 16.7
* Adds News SEO data to the new json head fields.
* removed a deprecated filter
* moved present logic to get method
* added key and tag format to make the presenter compatible with the `Abstract_Indexable_Tag_Presenter` that's new in free 16.7
by default, this PR doesn't do anything, because empty values are not output in the JSON head fields.
* access a post via the rest API; 
* visit https://basic.wordpress.test/wp-json/wp/v2/posts
output starts with [{"id":xxxxx -> use xxxxx as the Id for the next steps.
* visit http://[your-wordpress-server]/wp-json/wp/v2/posts/xxxxx
* copy & paste the …

P2 1093 implement abstract indexable presenter

---

classes/option.php
composer.json
composer.lock

* Update dev tools
* Update dev tools
... which includes PHP Parallel Lint by design, so no need to require it separately anymore.
Refs:
* https://github.com/Yoast/yoastcs/releases
* https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases
* https://github.com/PHPCompatibility/PHPCompatibilityWP/releases
The `vendor` directory is already ignored via the YoastCS ruleset, so no need to explicitly ignore it.
* _N/A_ if the (CS part of the) build passes we're good.

Composer: update to YoastCS 2.2.0

---

classes/schema.php
classes/wpseo-news.php
integration-tests/schema-test.php

* Add Schema Article News subtypes (`ReviewNewsArticle`, `AnalysisNewsArticle`, `AskPublicNewsArticle`, `BackgroundNewsArticle`, `OpinionNewsArticle`, `ReportageNewsArticle`). 
**Please note** that we no longer automatically add `NewsArticle` for every article automatically as you can now configure 
all of that in the Content Types settings.
* Needs https://github.com/Yoast/wordpress-seo/pull/17479 to work.
* Test in conjunction with https://github.com/Yoast/wordpress-seo/pull/17479
* The Schema article dropdown on post pages should have extra added `News:` article types, and this should propagate through to the frontend.
Fixes PRODUCT-166

Add Schema Article News subtypes

---

.travis.yml
composer.json
composer.lock
integration-tests/admin-page-test.php
integration-tests/schema-test.php
integration-tests/sitemap-images-test.php
integration-tests/sitemap-test.php
phpunit-integration.xml.dist
phpunit.xml.dist

* Update test setup
* Updates test setup
See the [Make Core dev-note about the test changes](https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/) for the context of these changes.
PHPUnit recently released version 9.5.10 and 8.5.21.
This contains a particular (IMO breaking) change:
> * PHPUnit no longer converts PHP deprecations to exceptions by default (configure `convertDeprecationsToExceptions="true"` to enable this)
Let's unpack this:
Previously (PHPUnit < 9.5.10/8.5.21), if PHPUnit would encounter a PHP native deprecation notice, it would:
1. Show a test which causes a deprecation notice to be thrown as **"errored"**,
2. Show the **first** deprecation notice it encountered and
3. PHPUnit …

Update (fix) test setup

---

classes/schema.php
integration-tests/schema-test.php

* https://github.com/Yoast/wordpress-seo/pull/17549 has deprecated the `wpseo_schema_article_post_types` filter. We want to remove the code hooking into that to prevent any warning.
* Removes function hooking into the deprecated `wpseo_schema_article_post_types` filter.
*
* Install and activate Free 17.6-RC2
* Install and activate News SEO 13.1-RC1
* make sure you have `define( 'WP_DEBUG', true );` in your config
* visit `SEO` > `Search Appearance`, tab `Content types` and see that you can find such notice:
```
Deprecated: wpseo_schema_article_post_types is deprecated since version WPSEO 17.6 with no alternative available. Every post type supporting authors will …
```

DUPP-61 Remove code hooking into the deprecated `wpseo_schema_article_post_types` filter

---

classes/wpseo-news.php
integration-tests/wpseo-news-test.php

* We want to update the minimum Free update version to 17.6
* Updates the minimum required Yoast SEO version to 17.6
*
* Test against  Free >= 17.6-RC1 to see that News SEO is available in the Sidebar under `SEO`
* Test against  Free < 17.6-RC1 to see that News SEO is not available  in the Sidebar under `SEO` and you get and admin notice saying "Please upgrade the Yoast SEO plugin to the latest version to allow the News SEO module to work."
*
*
Fixes [DUPP-65]
[DUPP-65]: https://yoast.atlassian.net/browse/DUPP-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

DUPP-65 Update minimum required Free version to 17.6

---

classes/sitemap.php

* Fixes DUPP-67 in a performant manner by joining on a virtual table composed of all excluded terms and then checking if that table has no matches.
* Fixes a bug where items with multiple terms would only be excluded if all terms were excluded rather than any term.
* A join on a virtual table is used to avoid full table scans and dependent sub-queries.
* See https://yoast.atlassian.net/browse/DUPP-67
* The news sitemaps
Fixes https://yoast.atlassian.net/browse/DUPP-67

[DUPP-67] Fix exclude join query

---

classes/admin-page.php
classes/sitemap.php

* We want to remove attachments and non-indexed post types from the settings page.
* [See slack for reference](https://yoast.slack.com/archives/CGUL0LDQS/p1636463831028500). 
* Excludes attachments and non-indexed post types from the possible post types to include in the News Sitemap.
*
* Install and activate Yoast SEO 17.6
* install and activate this branch
* install and activate Elementor
* visit `SEO` > `News SEO`
* check that under "Post Types to include in News Sitemap":
* you can't see `Media (attachement)` anymore
* you can see `Landing Pages (e-landing-page)` but not `My Templates (elementor_library)` since the latter don't  get indexables.
QA can test this PR by …

DUPP-73 Remove not indexed post types from sitemap

---

classes/sitemap.php

*
* Fixes an un released bug where a sitemap might not include all the expected items when filtering by many terms.
*
* Install and activate Yoast SEO 17.6 RC4.
* Install and activate Yoast News SEO 13.0
* Install and activate Yoast Local 14.2-RC1.
* Install and activate Yoast Test Helper
* Enable post types & taxonomies in Yoast Test Helper
* Create several different post types/taxonomies/CPT(locations/books) and custom taxonomies
* Mark them as types to include in News Sitemap
* Mark some terms to be excluded from News sitemap.
* Check News sitemap xml and make a screenshot 
* Upgrade News SEO to 13.1 -RC5
* Check News sitemap xml after upgrading and compare with …

DUPP-78 Fix bug in query

---

.travis.yml

* Improve/fix CI
* Improve/fix CI
Composer 2.2 contains a a bug/over-optimization, which causes the install with changed, but compatible requirements to error out on "conflicting" requirements.
This commit puts a work-around for this in place.
It is recommended to revert this commit if/when the Composer bug has been fixed and a new version has been released.
Ref:
* Bug report: https://github.com/composer/composer/issues/10394
* Probable cause: https://github.com/composer/composer/pull/9620
* Similar fix in YoastSEO: https://github.com/Yoast/wordpress-seo/commit/b3999428193d5cdcdd0758dcb7dc060e6992c507
* _N/A_ If the build passes, we're good.

Travis: fix integration test build on PHP >= 8.0

---

.travis.yml

* Simplify CI
* Simplify CI
Follow up on #731
This reverts commit 3a51b97ab6db8399c25da14c3ea18c2330a3d7ea.
Composer 2.2.3 has been released which contains a fix for the overly greedy optimization pass which was introduced in Composer 2.2.0.
With this fix in place, the previously introduced work-around for Composer 2.2 is no longer needed.
Refs:
* https://github.com/composer/composer/releases/tag/2.2.3
* https://github.com/composer/composer/issues/10394
* _N/A_ If the build passes, we're good.

Travis: remove "fix integration test build on PHP >= 8.0"

---

integration-tests/admin-page-test.php

* Compatibility with PHP 8.1/WP 5.9
* Compatibility with PHP 8.1/WP 5.9
Tests: minor fix to work round WP native issue with a not-as-yet-fixed PHP 8.1 deprecation notice.
If the `$plugin_page` is not set, WP will generate a `preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated` deprecation notice as of PHP 8.1.
By "mocking" the value of the `$plugin_page`, we get round that.
* The issue (test errroing out) can be seen when running the integration tests against PHP 8.1 and will be gone with this fix in place.

PHP 8.1 | Tests: minor fix to work round WP native issue

---

.travis.yml
README.md
classes/wpseo-news.php
integration-tests/wpseo-news-test.php

* On January 25, 2022, WordPress 5.9 was released. We've decided to go back to supporting only the latest 2 WP versions.
* Sets minimum required WordPress version to 5.8.
*
* Have WordPress 5.7 or lower installed. Be unable to update.
*
*
Fixes #

Set minimum WP version to 5.8 and tested up to to 5.9

---

integration-tests/framework/unittestcase.php

* For php8 compatibility we should avoid using reserved parameter names.
* Avoids usage of the reserved keywords (_object_ in this case) as parameters names
*
The changes should all be internal to methods, so no behaviour should be affected. For clarity, the areas touched are:
* Integration tests
*
*
Fixes [DUPP-341]
[DUPP-341]: https://yoast.atlassian.net/browse/DUPP-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix reserved keywords used as parameters names

---

.github/workflows/deploy.yml

Ensure that `coverage: none` is always used (except for when running Coverage) as it prevents problems with undesired extensions being installed/incorrectly configured.
`setup-php` has deprecated and replaced an environment variable in a recent release:
> Deprecated `COMPOSER_TOKEN` in favor of `GITHUB_TOKEN`
This updates the workflow for that change.
Refs:
* https://github.com/shivammathur/setup-php/releases/tag/2.21.0
* https://github.com/shivammathur/setup-php#github-composer-authentication
* _N/A_ If the build passes, we're good.

GH Actions: minor tweak

---

.github/workflows/cs.yml
.github/workflows/deploy.yml
.github/workflows/integrationtest.yml
.github/workflows/lint.yml
.github/workflows/unittest.yml

GitHub has deprecated the use of `set-output` (and `set-state`) in favour of new environment files.
This commit updates workflows to use the new methodology.
Refs:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
Caches used in GH Actions …

GH Actions: various tweaks

---

classes/meta-box.php
classes/sitemap.php

The deprecation of the `FILTER_SANITIZE_STRING` constant will be addressed at a later point, but is causing undue confusion for users, so for now, we'll be silencing the deprecation notices.
* _N/A_

CS: minor fixes

---

classes/admin-page.php
composer.json
composer.lock
tests/googlebot-news-presenter-test.php

* Removed the Translation "nag" from the plugin.

Remove our yoast i18n composer dependency

---

.github/workflows/integrationtest.yml
README.md
classes/wpseo-news.php
integration-tests/wpseo-news-test.php

* Sets minimum WordPress version to 6.0.
* Sets minimum WordPress version to 6.0.
*
*
*
*
Fixes #

Set minimum WP version to 6.0

---

README.md
package.json
yarn.lock

* Update plugin-grunt-tasks 2.3 => 2.4
* this will change the initial date format (to yyyy-mm-dd) used when creating a new RC,
* updates a dependancy from master to main
* updates the date format in README.md
* Updates the `plugin-grunt-tasks` dependency to 2.4 ( this will change the initial date format to yyyy-mm-dd when creating a new RC).
* Updates the date format in README.md.
* Updates a dependency from `master` to `main`.
*
* verify README.md
*
*
Fixes #

update plugin-grunt-tasks to 2.4 and update date format in readme.md

---

classes/sitemap.php

* Using the `&` character in the publication name breaks the xml sitemap: we want to avoid that.
* Fixes a bug where using the `&` character in the publication name would break the XML sitemap.
*
* Go to `Yoast SEO` -> `News SEO`
* In `Google News Publication Name` insert a string which comprises a `&`
* Create a new post
* Go to `Yoast SEO` -> `Settings` -> `Site Features` in the `APIs` section
* Ensure the `XML Sitemaps` card is enabled and click on the `View the XML sitemap` button
* Click on the `news-sitemap-xml` URL
* Without this PR, a blank page (or a page with an error) is rendered
* With this PR, an XML sitemap with (at least) a link to your newly-created post …

Fix special characters in publication name

---

classes/sitemap.php

* We want to add a filter to allow users to append custom content to `Yoast SEO News` XML sitemap.
* Adds a `wpseo_news_sitemap_content` filter to append custom content to the XML sitemap. Props to @wccoder.
* N/A
**Preliminary steps**
* In your theme's `functions.php` add the following lines:
```
function add_sitemap_news_content($content = '') {
return "\n";
}
add_filter('wpseo_news_sitemap_content', 'add_sitemap_news_content');
```
* Go to `Yoast SEO` -> `Settings`
* In `Site features` make sure you have `XML sitemaps` feature active
* Go to `Yoast SEO` -> `News SEO`
* Make sure `Posts` checkbox is selected under `Post types to include in News sitemap`
* Create a new …

Adding filter so custom entries can be added to the news sitemap.

---

.github/workflows/deploy.yml
.github/workflows/integrationtest.yml
.github/workflows/lint.yml
.github/workflows/unittest.yml
README.md
composer.json
composer.lock
wpseo-news.php

This PR depends on https://github.com/Yoast/wordpress-seo/pull/19948.
After that one has been merged, we need to update this so it points to  Free `trunk` (`composer require yoast/wordpress-seo:dev-trunk@dev --dev`) and check that GH action still pass.
* 
* Drops compatibility with PHP 5.6, 7.0 and 7.1.
*
* Verify the GH actions pass
* install on a PHP 5.6 environment
* visit the Plugins page
* see that you get the same message and you can't activate the plugin, as it happens here for Free and Premium:
* the same should happen with 7.0 and 7.1
**note**: the above may be tricky to test. I can see 5.6 as a choice in Local by Flywheel, but I know it's not the case for others …

Drop compatibility with PHP 5.6, 7.0 and 7.1

---

.github/workflows/integrationtest.yml
README.md
classes/wpseo-news.php
integration-tests/wpseo-news-test.php
wpseo-news.php

*
* Sets the minimum supported WordPress version to 6.1.
* N/A
*
* N/A
*
Fixes #

Set the minimum supported WordPress version to 6.1

---

classes/sitemap.php
tests/news-test.php

* [Sitemaps] Minor improvement for sites not using `utf-8` character encoding
* Alphabetically sort `use` statements.
* The default value of the `$flags` parameter has changed in PHP 8.1. Passing the value explicitly will ensure that the resulting escaped value will be the same PHP cross-version.
* Passing the `$encoding` parameter is also important as not all WP sites use `utf-8` as the character encoding.
* Lastly, we want to prevent the value from being double encoded, so `$double_encode` should be set to `false`.
* On a site not using `utf-8` char encoding, the site name in the sitemap will now have a smaller chance of getting mangled.

CS/QA: various tweaks

---

.github/workflows/cs.yml
.github/workflows/js.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Only run the workflows when there is a chance that the result of the workflow run will be different from before.
The path selection is set up to cast a wide net to make the risk of the workflows not running when the build could potentially break as small as possible.
This means that, aside from files of the type being checked in the workflow changing, the workflow will also run when:
* The configuration used changes.
* Dependencies used in the workflow may potentially have changed.
* Composer scripts used in the workflow may potentially have changed.
* Shell scripts used in the workflow have changed.
* The workflow itself changes.
* Miscellaneous related files have changed.
Note: the lists of …

GH Actions: run workflows more selectively

---

classes/wpseo-news.php
tests/bootstrap.php
tests/news-test.php

*
* Fixes a bug where a warning would be thrown on activation.
* The root cause of the problem was that we run the upgrade manager on the constructor of `WPSEO_News`, while the class initializes the options on the `init` hook. I moved the upgrade manager to the `admin_init` hook which fires after `init` so the options will be there when needed.
* make sure you are in a clean environment where News have never been run. If not, deleting `wpseo_news` from the `wp_option` table should be enough.
* install and activate Query Monitor
* install and activate Yoast SEO
* install and activate News SEO
* without this patch:
* you should see a couple of warnings in Query monitor …

Fix activation warning
